### PR TITLE
returns http 400 bad request instead of 500 when it's a query plan error

### LINKED ISSUE #1287: Gateway returns Http 500 instead 400 for invalid graphql request field
**Describe the bug**
The Apollo Router (gateway) returns a http 500 error when I type a invalid field name. Based on GraphQL over http spec, such an error should give http 400 bad request https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#unparseable-or-invalid-request-body
image

**To Reproduce**

- Put an invalid character in the request field

**Expected behavior**
Http 400 will return instead of 500

**Output**
If applicable, add output to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by bnjjj**
close #1287

### CODE REVIEW

File: apollo-router/src/services/router_service.rs [hunk 1]
```diff
@@ -221,7 +221,7 @@ where
 
             Ok(RouterResponse::builder()
                 .errors(errors)
-                .status_code(StatusCode::INTERNAL_SERVER_ERROR)
+                .status_code(StatusCode::BAD_REQUEST)
```
Comment (Geal) [inline apollo-router/src/services/router_service.rs:224]: IIRC there are some query planner errors that could be a 500? Like if the JS query planner does not answer? Can we discriminate the errors here?

Comment (bnjjj) [reply apollo-router/src/services/router_service.rs]: Good point ! Fixed

**Review by garypen — APPROVED** [review]
