### PR TITLE
Remove the response mutex, refactor fetch_node and fix response merging

### LINKED ISSUE #248: merging entities by subgraph response index puts data in the wrong object
Related:
- https://github.com/apollographql/router/issues/47 (this issue was uncovered by integration tests)

With the following query:

```graphql
 query {
  me {
    name {
      first
      last
    }
  }
  topProducts {
    name
    ... on Book {
      details {  
        pages
      }
    }
  }
}
```

I am getting the following logs:

```
[2mOct 29 13:54:49.052[0m [32m INFO[0m apollo_router_core::federated: query: None => 
      query {
        me {
          name {
            first
            last
          }
        }
        topProducts {
          name
          ... on Book {
            details {  
              pages
            }
          }
        }
      }
    
[2mOct 29 13:54:49.053[0m [32m INFO[0m apollo_router_core::federated: plan: Parallel {
    nodes: [Fetch(FetchNode {
        service_name: "accounts",
        requires: None,
        variable_usages: [],
        operation: "{me{name{first last}}}"
    }), Sequence {
        nodes: [Fetch(FetchNode {
            service_name: "product",
            requires: None,
            variable_usages: [],
            operation: "{topProducts{__typename ...on Book{__typename isbn details{pages}}...on Furniture{name}}}"
        }), Flatten(FlattenNode {
            path: Path([Key("topProducts"), Flatten]),
            node: Fetch(FetchNode {
                service_name: "books",
                requires: Some([InlineFragment(InlineFragment {
                    type_condition: Some("Book"),
                    selections: [Field(Field {
                        alias: None,
                        name: "__typename",
                        selections: None
                    }), Field(Field {
                        alias: None,
                        name: "isbn",
                        selections: None
                    })]
                })]),
                variable_usages: [],
                operation: "query($representations:[_Any!]!){_entities(representations:$representations){...on Book{title year}}}"
            })
        }), Flatten(FlattenNode {
            path: Path([Key("topProducts"), Flatten]),
            node: Fetch(FetchNode {
                service_name: "product",
                requires: Some([InlineFragment(InlineFragment {
                    type_condition: Some("Book"),
                    selections: [Field(Field {
                        alias: None,
                        name: "__typename",
                        selections: None
                    }), Field(Field {
                        alias: None,
                        name: "title",
                        selections: None
                    }), Field(Field {
                        alias: None,
                        name: "year",
                        selections: None
                    }), Field(Field {
                        alias: None,
                        name: "isbn",
                        selections: None
                    })]
                })]),
                variable_usages: [],
                operation: "query($representations:[_Any!]!){_entities(representations:$representations){...on Book{name}}}"
            })
        })]
    }]
}

[2mOct 29 13:54:49.057[0m [32m INFO[0m [1mfederated_query[0m: apollo_router_core::federated: fetch(accounts):
"{topProducts{__typename ...on Book{__typename isbn details{pages}}...on Furniture{name}}}" with variables {}
=> Some(Response { label: None, data: Object({"topProducts": Array([Object({"__typename": String("Furniture"), "name": String("Table")}), Object({"__typename": String("Furniture"), "name": String("Couch")}), Object({"__typename": String("Furniture"), "name": String("Chair")}), Object({"__typename": String("Book"), "isbn": String("0262510871"), "details": Null}), Object({"__typename": String("Book"), "isbn": String("0136291554"), "details": Null})])}), path: None, has_next: None, errors: [], extensions: {} })

[2mOct 29 13:54:49.058[0m [32m INFO[0m apollo_router_core::federated: fetch(product):
"{me{name{first last}}}" with variables {}
=> Some(Response { label: None, data: Object({"me": Object({"name": Object({"first": String("Ada"), "last": String("Lovelace")})})}), path: None, has_next: None, errors: [], extensions: {} })

[2mOct 29 13:54:49.059[0m [32m INFO[0m apollo_router_core::federated: fetch(books):
"query($representations:[_Any!]!){_entities(representations:$representations){...on Book{title year}}}" with variables {"representations": Array([Object({"__typename": String("Book"), "isbn": String("0262510871")}), Object({"__typename": String("Book"), "isbn": String("0136291554")})])}
=> Some(Response { label: None, data: Object({"_entities": Array([Object({"title": String("Structure and Interpretation of Computer Programs"), "year": Number(1996)}), Object({"title": String("Object Oriented Software Construction"), "year": Number(1997)})])}), path: None, has_next: None, errors: [], extensions: {} })

[2mOct 29 13:54:49.060[0m [31mERROR[0m apollo_router_core::federated: Fetch error: Subquery requires field 'title' but it was not found in the current response.
```

The issue here is that the global response has an array of products `[couch, chair, book, book]`, but when we do the query to the "books" subgraph, we use an array of 2 entities, and when they are merged by index, they are added to "couch" and "chair".

More context:

```graphql
{topProducts{__typename ...on Book{__typename isbn details{pages}}...on Furniture{name}}}
```
 on products returns the array
 
 ```
 Object({"__typename": String("Furniture"), "name": String("Table")}), Object({"__typename": String("Furniture"), "name": String("Couch")}), Object({"__typename": String("Furniture"), "name": String("Chair")}), Object({"__typename": String("Book"), "isbn": String("0262510871"), "details": Null}), Object({"__typename": String("Book"), "isbn": String("0136291554"), "details": Null}
 ```

Then the query 

```graphql
query($representations:[_Any!]!){_entities(representations:$representations){...on Book{title year}}}
```
 with variables 
 
 ```
 {"representations": Array([Object({"__typename": String("Book"), "isbn": String("0262510871")}), Object({"__typename": String("Book"), "isbn": String("0136291554")})])}
 ```

returns

```
Array([Object({"title": String("Structure and Interpretation of Computer Programs"), "year": Number(1996)}), Object({"title": String("Object Oriented Software Construction"), "year": Number(1997)})]
```

I started taking care of it by generating the representations with a list of paths to put the data into

### PR DESCRIPTION
**Pull request by Geal**
Fix: #248

This PR gets rid of the response mutex and simplify response merging.

- separate tasks of `fetch_node` in different methods to extract the mutex usage more easily
- refactor `execute_recursively` to merge response data incrementally from smaller subsets of the response
- use `FuturesUnordered` to transform parallel queries in a stream of subgraph responses that are then merged one by one
- generate with representations data a path for each entity, so that we know exactly where to insert it in the response data. This fixes #248

### CODE REVIEW

**Comment by Geal** [comment]
https://app.circleci.com/pipelines/github/apollographql/router/686/workflows/d35d0548-58ed-4175-b643-4b322849d157/jobs/3854/parallel-runs/0/steps/0-113 <- that is a funny error, because the two responses are apparently the same :smile:

**Comment by Geal** [comment]
ok so, it passes the tests and lints, so good news. It needs a bit more cleanup now, and some perf tests, and that should be good to go

**Comment by Geal** [comment]
Benchmark:

## main at a296efbfde20c92ca24785b32c3b31b0636306fa

```
$ hey -m POST -H 'Content-type: application/json' -d '{"query":"query  { products(limit: 2) { review { body } re
lated { price price1 price2 price3 } } }\n","price price1 price2 price3 variables":{}}' -n 300000 -c 1000 http://127.0.0.1:4000/        
                                                                                                                                        
Summary:                                                                                                                                
  Total:        40.7823 secs                                                                                                            
  Slowest:      4.7580 secs                                                                                                             
  Fastest:      0.0009 secs                                                                                                             
  Average:      0.1238 secs                                                                                                             
  Requests/sec: 7356.1269                                                                                                               
                                                                                                                                        
                                                                                                                                        
Response time histogram:                                                                                                                
  0.001 [1]     |                                                                                                                       
  0.477 [277744]        |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                                       
  0.952 [1987]  |                                                                                                                       
  1.428 [9771]  |■                                                                                                                      
  1.904 [9931]  |■                                                                                                                      
  2.379 [37]    |                                                                                                                       
  2.855 [255]   |                                                                                                                       
  3.331 [259]   |                                                                                                                       
  3.807 [10]    |                                                                                                                       
  4.282 [3]     |                                                                                                                       
  4.758 [2]     |                                                                                                                       
                                                                                                                                        
                                                                                                                                        
Latency distribution:                                                                                                                   
  10% in 0.0139 secs                                                                                                                    
  25% in 0.0165 secs                                                                                                                    
  50% in 0.0206 secs                                                                                                                    
  75% in 0.0248 secs                                                                                                                    
  90% in 0.0301 secs                                                                                                                    
  95% in 1.3433 secs                                                                                                                    
  99% in 1.5689 secs                                                                                                                    
                                                                                                                                        
Details (average, fastest, slowest):                                                                                                    
  DNS+dialup:   0.0001 secs, 0.0009 secs, 4.7580 secs                                                                                   
  DNS-lookup:   0.0000 secs, 0.0000 secs, 0.0000 secs                                                                                   
  req write:    0.0000 secs, 0.0000 secs, 0.0144 secs                                                                                   
  resp wait:    0.0270 secs, 0.0000 secs, 1.8670 secs                                                                                   
  resp read:    0.0966 secs, 0.0000 secs, 4.7502 secs                                                                                   
                                                                                                                                        
Status code distribution:                                                                                                               
  [200] 300000 responses
```

## This PR at 4229fa8fd1889499b76d4bf858f1456338c12545

```
$ hey -m POST -H 'Content-type: application/json' -d '{"query":"query  { products(limit: 2) { review { body } re
lated { price price1 price2 price3 } } }\n","price price1 price2 price3 variables":{}}' -n 300000 -c 1000 http://127.0.0.1:4000/        
                                                                                                                                        
Summary:                                                                                                                                
  Total:        38.6082 secs                                                                                                            
  Slowest:      4.4451 secs                                                                                                             
  Fastest:      0.0014 secs                                                                                                             
  Average:      0.1174 secs                                                                                                             
  Requests/sec: 7770.3751                                                                                                               
                                                                                                                                        
                                                                                                                                        
Response time histogram:                                                                                                                
  0.001 [1]     |                                                                                                                       
  0.446 [277055]        |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                                       
  0.890 [2098]  |                                                                                                                       
  1.334 [10673] |■■                                                                                                                     
  1.779 [9558]  |■                                                                                                                      
  2.223 [48]    |                                                                                                                       
  2.668 [312]   |                                                                                                                       
  3.112 [242]   |                                                                                                                       
  3.556 [1]     |                                                                                                                       
  4.001 [8]     |                                                                                                                       
  4.445 [4]     |                                                                                                                       
                                                                                                                                        
                                                                                                                                        
Latency distribution:                                                                                                                   
  10% in 0.0132 secs                                                                                                                    
  25% in 0.0158 secs                                                                                                                    
  50% in 0.0195 secs                                                                                                                    
  75% in 0.0235 secs                                                                                                                    
  90% in 0.0280 secs                                                                                                                    
  95% in 1.2608 secs                                                                                                                    
  99% in 1.4574 secs                                                                                                                    
                                                                                                                                        
Details (average, fastest, slowest):                                                                                                    
  DNS+dialup:   0.0001 secs, 0.0014 secs, 4.4451 secs                                                                                   
  DNS-lookup:   0.0000 secs, 0.0000 secs, 0.0000 secs                                                                                   
  req write:    0.0000 secs, 0.0000 secs, 0.0145 secs                                                                                   
  resp wait:    0.0251 secs, 0.0000 secs, 1.5970 secs                                                                                   
  resp read:    0.0922 secs, 0.0000 secs, 4.0642 secs                                                                                   
                                                                                                                                        
Status code distribution:                                                                                                               
  [200] 300000 responses
```

So it is slightly faster. Honestly I was expecting it to be a bit slower, because I have not started to optimize it yet, but that means it should be good to merge as is (at least on the performance side)

**Comment by BrynCooke** [comment]
It would be good to perf test this against a more realistic sized response. Something around the 5kb response size maybe?

**Comment by Geal** [comment]
Good idea. What's the shape of the 5kB response? One big field? In that case there should not be much difference.
For deeply nested responses with lots of parallel requests we should see easily if there's a perf regression

**Comment by BrynCooke** [comment]
This is the test that we are using for nightlies:
```
subgraph-response-time=0
subgraph-response-field-size=32
subgraph-depth=5
subgraph-breadth=2
subgraph-fields=100
```
I kicked off a run on the distributed infra for comparison:
main: https://apollographql.grafana.net/d/dffCG6n7k/perf?orgId=1&from=1639100852000&to=1639101099000
refactor-fetch: https://apollographql.grafana.net/d/dffCG6n7k/perf?orgId=1&from=1639126415000&to=1639126640000

Possibly a drop from 7k rps peak (main) to 5.5k rps (refactor-fetch)

**Comment by Geal** [comment]
great, that'll help me find the issues. Is there an easy way to extract the query corresponding to those parameters?
There's something weird in the graphs though, in the memory usage graph. The free memory is much lower for clients in the bench for this branch (I was looking at that graph because I wanted to check if the router was using more RAM)

File: apollo-router-core/src/query_planner/mod.rs [hunk 1]
```diff
@@ -395,48 +356,108 @@ impl FetchNode {
...
+                        serde_json::to_string(&entities).unwrap(),
+                    );
+
+                    if let Value::Array(array) = entities {
+                        let span = tracing::trace_span!("response_insert");
+                        let _guard = span.enter();
+
+                        let mut value = Value::default();
+
+                        let paths = paths.unwrap();
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:439]: :screwdriver: Please don't use unwrap unless it is very obvious why you are unwrapping. Use `.expect("...")` and write a solid proof that this expect won't *ever* panic.

On top of that, it seems you don't need your field `paths` in the struct `Variables` to be an option at all. All collections in Rust have a function to check for emptiness (often called `is_empty()`). Unless you need to distinguish between `None` and `Some(empty_collection)`, you shouldn't wrap your collection into an Option. That is what I'm fixing in #257

File: apollo-router-core/src/query_planner/mod.rs [hunk 2]
```diff
@@ -395,48 +356,108 @@ impl FetchNode {
...
+        let query_span = tracing::info_span!("subfetch", service = service_name.as_str());
 
-                    Ok(())
-                }
-                None => Err(FetchError::SubrequestNoResponse {
+        let Variables { variables, paths } =
+            self.make_variables(data, current_dir, request, schema)?;
+
+        // We already checked that the service exists during planning
+        let fetcher = service_registry.get(service_name).unwrap();
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:384]: :yarn: proofs inside the expect

```suggestion
        let fetcher = service_registry.get(service_name).expect("we already checked that the service exists during planning; qed");
```

File: apollo-router-core/src/query_planner/mod.rs [hunk 3]
```diff
@@ -395,48 +356,108 @@ impl FetchNode {
...
+            }
+
+            Err(FetchError::ExecutionInvalidContent {
+                reason: "Missing key `_entities`!".to_string(),
+            })
+        } else {
+            let span = tracing::trace_span!("response_insert");
+            let _guard = span.enter();
+
+            Ok(Value::from_path(current_dir, data))
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:460]: :screwdriver:  As per our ADR on telemetry, tracing's spans should be place on the source function and not the caller

File: apollo-router-core/src/query_planner/mod.rs [hunk 4]
```diff
@@ -395,48 +356,108 @@ impl FetchNode {
...
+        let Response { data, .. } = subgraph_response;
+
+        if self.requires.is_some() {
+            // we have to nest conditions and do early returns here
+            // because we need to take ownership of the inner value
+            if let Value::Object(mut map) = data {
+                if let Some(entities) = map.remove("_entities") {
+                    tracing::trace!(
+                        "Received entities: {}",
+                        serde_json::to_string(&entities).unwrap(),
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:430]: :information_source:  This is evaluated even if the formatting is not done.

:screwdriver: Use `{:?}` instead. We don't need to format to json for debugging.

File: apollo-router-core/src/query_planner/selection.rs [hunk 5]
```diff
@@ -42,23 +42,17 @@ pub(crate) struct InlineFragment {
     selections: Vec<Selection>,
 }
 
-pub(crate) fn select(
+#[cfg(test)]
+pub(crate) fn select<'a>(
```
Comment (cecton) [inline apollo-router-core/src/query_planner/selection.rs:46]: :screwdriver: Move this function to the tests module directly

:yarn: Check if you can update the tests and remove it entirely.

File: apollo-router-core/src/json_ext.rs [hunk 6]
```diff
@@ -138,9 +47,20 @@ impl ValueExt for Value {
...
+                a.extend(b.into_iter());
+            }
+            (_, Value::Null) => {}
+            (Value::Object(_), Value::Array(_)) => {
+                #[cfg(debug)]
+                panic!("trying to replace an object with an array");
+            }
+            (Value::Array(_), Value::Object(_)) => {
+                #[cfg(debug)]
+                panic!("trying to replace an object with an array");
```
Comment (cecton) [inline apollo-router-core/src/json_ext.rs:63]: :screwdriver: Use `failfast_debug!()` instead. Otherwise the debug build will behave differently than the release build.

:screwdriver: The second log is upside down

```suggestion
            (Value::Object(_), Value::Array(_)) => {
                failfast_debug!("trying to replace an object with an array");
            }
            (Value::Array(_), Value::Object(_)) => {
                failfast_debug!("trying to replace an array with an object");
```

File: apollo-router-core/src/json_ext.rs [hunk 7]
```diff
@@ -138,9 +47,20 @@ impl ValueExt for Value {
                 }
             }
             (Value::Array(a), Value::Array(mut b)) => {
-                for ((_index, b_value), a_value) in b.drain(..).enumerate().zip(a.iter_mut()) {
+                for (b_value, a_value) in b.drain(..min(a.len(), b.len())).zip(a.iter_mut()) {
```
Comment (cecton) [inline apollo-router-core/src/json_ext.rs:50]: :screwdriver: Zip already zips to the shortest https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.zip

```suggestion
                for (b_value, a_value) in b.drain(..).zip(a.iter_mut()) {
```

File: apollo-router-core/src/json_ext.rs [hunk 8]
```diff
@@ -35,94 +25,13 @@ pub trait ValueExt {
     /// values in `self`.
     #[track_caller]
     fn is_subset(&self, superset: &Value) -> bool;
+
+    /// create a Value by inserting a value at a subpath
```
Comment (cecton) [inline apollo-router-core/src/json_ext.rs:29]: :screwdriver: please spell things properly in doc.

```suggestion
    /// Create a `Value` by inserting a value at a subpath.
```

**Review by cecton — CHANGES_REQUESTED** [review]

File: apollo-router-core/src/json_ext.rs [hunk 9]
```diff
@@ -212,6 +132,160 @@ impl ValueExt for Value {
             (a, b) => a == b,
         }
     }
+
+    /// insert a specific value at a subpath
+    ///
+    /// this will create objects, arrays and null nodes as needed if they
+    /// are not present: the resulting Value is meant to be merged with an
+    /// existing one that contains those nodes
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/json_ext.rs:140]: good point, internal documentation should be as readable as public documentation, especially if it can be made public later

File: apollo-router-core/src/json_ext.rs [hunk 10]
```diff
@@ -390,30 +464,23 @@ mod tests {
 
     #[test]
     fn test_get_at_path() {
-        let mut json = json!({"obj":{"arr":[{"prop1":1},{"prop1":2}]}});
+        let json = json!({"obj":{"arr":[{"prop1":1},{"prop1":2}]}});
         let path = Path::from("obj/arr/1/prop1");
-        let result = json.get_at_path(&path).unwrap();
+        let result = select_values(&path, &json).unwrap();
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/json_ext.rs:469]: I wanted to keep the code close to what it was before, so `select_values` had the same shape as the previous `select` function, but you're right, it makes more sense to put it in the trait

File: apollo-router-core/src/query_planner/mod.rs [hunk 11]
```diff
@@ -79,103 +81,127 @@ impl QueryPlan {
...
             )
             .await;
 
-        // TODO: this is not great but there is no other way
-        Arc::try_unwrap(response)
-            .expect("todo: how to prove?")
-            .into_inner()
+        let mut response = Response::builder().build();
+        response.data = value;
+        response.errors = errors;
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:99]: yep, the builder is there, we might as well use it :smile:

File: apollo-router-core/src/query_planner/mod.rs [hunk 12]
```diff
@@ -79,103 +81,127 @@ impl QueryPlan {
...
         current_dir: &'a Path,
         request: Arc<Request>,
         service_registry: Arc<dyn ServiceRegistry>,
         schema: Arc<Schema>,
-    ) -> future::BoxFuture<()> {
+        parent_value: &'a Value,
+    ) -> future::BoxFuture<(Value, Vec<Error>)> {
         Box::pin(async move {
             tracing::trace!("Executing plan:\n{:#?}", self);
+            let mut value = Value::default();
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:116]: :+1:

File: apollo-router-core/src/query_planner/mod.rs [hunk 13]
```diff
@@ -79,103 +81,127 @@ impl QueryPlan {
...
+                        errors.extend(err.into_iter());
                     }
                 }
                 PlanNode::Parallel { nodes } => {
-                    future::join_all(nodes.iter().map(|plan| {
-                        plan.execute_recursively(
-                            Arc::clone(&response),
-                            current_dir,
+                    async {
+                        let mut resv = Value::default();
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:139]: right, I think it could take that value. I'll look at it more closely before changing it, because I suspect this part is the cause of the perf regression

File: apollo-router-core/src/query_planner/mod.rs [hunk 14]
```diff
@@ -79,103 +81,127 @@ impl QueryPlan {
...
+                        value.deep_merge(resv);
+                    }
+                    .instrument(tracing::info_span!("parallel"))
+                    .await;
+                }
+                PlanNode::Flatten(FlattenNode { path, node }) => {
+                    let (v, err) = node
+                        .execute_recursively(
+                            // this is the only command that actually changes the "current dir"
+                            path,
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:170]: The join is done on the returned value: https://github.com/apollographql/router/pull/250/files#diff-346a32f288e83dab64a10a4aef284a2e2a23ef77419ec48c683c6e53871e522aR179

The fiux for #248 is in the way representations are generated in `make_variables`:
https://github.com/apollographql/router/pull/250/files#diff-346a32f288e83dab64a10a4aef284a2e2a23ef77419ec48c683c6e53871e522aR323

for each variable, we get the exact path to insert it. So for the query `{topProducts{__typename ...on Book{__typename isbn details{pages}}...on Furniture{name}}}` if we have `[Chair, Book, Chair]`, the query to the books subgraph will have only one element, but we know we need to put it at index 1.

File: apollo-router-core/src/query_planner/mod.rs [hunk 15]
```diff
@@ -79,103 +81,127 @@ impl QueryPlan {
...
                         )
-                    }))
-                    .instrument(tracing::info_span!("parallel"))
-                    .await;
+                        .instrument(tracing::trace_span!("flatten"))
+                        .await;
+
+                    value = Value::from_path(current_dir, v);
+                    errors.extend(err.into_iter());
                 }
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:181]: it is mainly cosmetic, it made more sense to me to have all the cases that recurse together, and the terminating case at the end. I can put it back if you want

File: apollo-router-core/src/query_planner/mod.rs [hunk 16]
```diff
@@ -79,103 +81,127 @@ impl QueryPlan {
...
+                        Ok(v) => value = v,
                         Err(err) => {
                             failfast_error!("Fetch error: {}", err);
-                            response
-                                .lock()
-                                .await
-                                .errors
-                                .push(err.to_graphql_error(Some(current_dir.to_owned())));
+                            errors.push(err.to_graphql_error(Some(current_dir.to_owned())));
+                            return (value, errors);
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:198]: :+1:

File: apollo-router-core/src/query_planner/mod.rs [hunk 17]
```diff
@@ -271,121 +297,56 @@ pub(crate) struct FetchNode {
     operation: String,
 }
 
+struct Variables {
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:300]: right, that would make sens. Do you mean a module in a separate file, or their own module inside this one?

File: apollo-router-core/src/query_planner/mod.rs [hunk 18]
```diff
@@ -271,121 +297,56 @@ pub(crate) struct FetchNode {
...
+                            reason: "not an object".to_string(),
+                        })),
                     })
-                }
-                None => Err(FetchError::SubrequestNoResponse {
-                    service: service_name.to_string(),
-                }),
-            }
+                    .collect::<Result<Vec<_>, _>>()
+                    .unwrap(),
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:338]: nice catch, thanks

File: apollo-router-core/src/query_planner/mod.rs (hunk 2 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:384]: :+1:

File: apollo-router-core/src/query_planner/mod.rs (hunk 15 above)
[the remark this answers is not in the document]
Comment (cecton) [reply apollo-router-core/src/query_planner/mod.rs:181]: What you said sounds reasonable. Keep it there

File: apollo-router-core/src/query_planner/mod.rs (hunk 4 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:430]: that's potentially a big perf improvement :smiley:

File: apollo-router-core/src/query_planner/mod.rs (hunk 1 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:439]: makes sense, I'll change that

File: apollo-router-core/src/query_planner/mod.rs (hunk 17 above)
[the remark this answers is not in the document]
Comment (cecton) [reply apollo-router-core/src/query_planner/mod.rs:300]: It's technically the same and I don't have preference (nor aversion) again big files so... as you prefer.

File: apollo-router-core/src/query_planner/mod.rs (hunk 3 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:460]: right, I was following the previous code on that, it's a good opportunity to change it

File: apollo-router-core/src/query_planner/mod.rs (hunk 4 above)
Comment (cecton) [reply apollo-router-core/src/query_planner/mod.rs:428]: I didn't mean too :rofl:

File: apollo-router-core/src/json_ext.rs (hunk 7 above)
Comment (Geal) [reply apollo-router-core/src/json_ext.rs:50]: :+1:

File: apollo-router-core/src/json_ext.rs (hunk 8 above)
Comment (Geal) [reply apollo-router-core/src/json_ext.rs:29]: right, thanks

File: apollo-router-core/src/json_ext.rs (hunk 7 above)
Comment (Geal) [reply apollo-router-core/src/json_ext.rs:50]: I don't know why I assume that I must pass two iterators of the same amount to zip. There must be some old scars of other languages there :sweat_smile:

File: apollo-router-core/src/query_planner/mod.rs (hunk 15 above)
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:182]: alright

File: apollo-router-core/src/query_planner/mod.rs (hunk 17 above)
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:300]: I'll leave in the same module for now then, it fits well with the rest of the query plan execution

[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:300]: same _file_, sorry

File: apollo-router-core/src/query_planner/mod.rs [hunk 19]
```diff
@@ -271,121 +297,56 @@ pub(crate) struct FetchNode {
...
-
-        if let Some(requires) = requires {
-            // We already checked that the service exists during planning
-            let fetcher = service_registry.get(service_name).unwrap();
-
-            let mut variables = Object::with_capacity(1 + variable_usages.len());
-            variables.extend(variable_usages.iter().filter_map(|key| {
+        request: &Arc<Request>,
+        schema: &Arc<Schema>,
+    ) -> Result<Variables, FetchError> {
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:312]: :+1:

File: apollo-router-core/src/query_planner/mod.rs [hunk 20]
```diff
@@ -271,121 +297,56 @@ pub(crate) struct FetchNode {
...
-                                    reason: "Received invalid type for key `_entities`!"
-                                        .to_string(),
-                                });
-                            }
+            let values_and_paths = select_values_and_paths(current_dir, data)?;
+            let mut paths = Vec::new();
+            let representations = Value::Array(
+                values_and_paths
+                    .into_iter()
+                    .flat_map(|(path, value)| match (value, requires) {
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:328]: nice catch

File: apollo-router-core/src/query_planner/mod.rs (hunk 4 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:428]: heh, accidentally faster is still faster, I'll take it :grin:

File: apollo-router-core/src/json_ext.rs (hunk 7 above)
Comment (cecton) [reply apollo-router-core/src/json_ext.rs:50]: One that fills the missing elements with `null`? :joy: 

There is a zip_longest in itertools if you ever need: https://docs.rs/itertools/0.10.3/itertools/trait.Itertools.html#method.zip_longest

File: apollo-router-core/src/query_planner/selection.rs (hunk 5 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/selection.rs:46]: :+1:

File: apollo-router-core/src/query_planner/mod.rs (hunk 17 above)
[the remark this answers is not in the document]
Comment (cecton) [reply apollo-router-core/src/query_planner/mod.rs:300]: That is fine by me either way. It was just a :yarn:

File: apollo-router-core/src/json_ext.rs [hunk 21]
```diff
@@ -212,6 +132,160 @@ impl ValueExt for Value {
...
         }
     }
+
+    /// Insert a specific value at a subpath.
+    ///
+    /// This will create objects, arrays and null nodes as needed if they
+    /// are not present: the resulting Value is meant to be merged with an
+    /// existing one that contains those nodes.
+    #[track_caller]
+    fn from_path(path: &Path, value: Value) -> Value {
```
Comment (Geal) [inline apollo-router-core/src/json_ext.rs:140]: it would make sense to add back an `insert_data` method following the same pattern, since in various places we create a `Value` to immediately merge it

File: apollo-router-core/src/json_ext.rs [hunk 22]
```diff
@@ -212,6 +132,160 @@ impl ValueExt for Value {
...
+    path: &'a Path,
+    data: &'a Value,
+) -> Result<Vec<&'a Value>, FetchError> {
+    Ok(select_values_and_paths(path, data)?
+        .into_iter()
+        .map(|r| r.1)
+        .collect())
+}
+
+fn iterate_path<'a>(
```
Comment (Geal) [inline apollo-router-core/src/json_ext.rs:222]: suggestion by @o0Ignition0o : using a visitor here would be great, it would help in refactoring the code in fetch_node

Comment (cecton) [reply apollo-router-core/src/json_ext.rs:222]: I'm not sure what he meant by visitor. Did you mean iterator?

Comment (o0Ignition0o) [reply apollo-router-core/src/json_ext.rs:222]: I meant a [visitor](https://rust-unofficial.github.io/patterns/patterns/behavioural/visitor.html)

File: apollo-router-core/src/json_ext.rs (hunk 7 above)
Comment (Geal) [reply apollo-router-core/src/json_ext.rs]: ok, so, this does not work, because [drain](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.drain) will drop all the elements that were not consumed once the iterator is dropped, while we actually want to append them afterwards, so I'll revert that change. Do you see another way to fix it?

> One that fills the missing elements with null? 

I'm pretty sure I picked up the habit to check lengths when I worked in C :sweat_smile:

Comment (cecton) [reply apollo-router-core/src/json_ext.rs:64]: :thinking: wow that was tricky!

Ok so I'm all in favor to move to itertool's zip_longest then. The algorithm will be much more readable!

File: apollo-router-core/src/json_ext.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/json_ext.rs:470]: done in b4d3aeb

File: apollo-router-core/src/query_planner/mod.rs (hunk 19 above)
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs]: 09da774

File: apollo-router-core/src/query_planner/mod.rs (hunk 17 above)
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs]: done in  d46e83e

File: apollo-router-core/src/query_planner/mod.rs [hunk 23]
```diff
@@ -271,121 +297,56 @@ pub(crate) struct FetchNode {
...
+                        (Value::Object(content), requires) => {
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs]: done in c2a8dc4

File: apollo-router-core/src/query_planner/mod.rs (hunk 20 above)
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs]: done in c2a8dc4

File: apollo-router-core/src/query_planner/mod.rs (hunk 1 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs]: done in 19cae6c

File: apollo-router-core/src/query_planner/mod.rs (hunk 3 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs]: done in 45c4df2

File: apollo-router-core/src/query_planner/mod.rs (hunk 4 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs]: done in 02b81b5

File: apollo-router-core/src/query_planner/selection.rs (hunk 5 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/selection.rs]: done in 6a2573b

File: apollo-router-core/src/json_ext.rs (hunk 7 above)
Comment (Geal) [reply apollo-router-core/src/json_ext.rs:64]: I'll take a look at zip_longest, I like the approach of returning an enum

**Comment by Geal** [comment]
I ran some quick benchmarks locally, with the same query:

```graphql
query { products(limit: 2, size: 32) { price pri
ce1 price2 price3 price4 price5 price6 price7 price8 price9 price10 price11 price12 price13 price14 price15 price16 price17 price18 price19 price20 price21 price22 price23 price24 price25 price26 price27 price28 price29 price30 price31 price32 price33 price34 price35 price36 price37 price38 price39 price40 price41 price42 price43 price44 price45 price46 price47 price48 price49 price50 price51 price52 price53 price54 price55 price56 price57 price58 price59 price60 price61 price62 price63 price64 price65 price66 price67 price68 price69 price70 price71 price72 price73 price74 price75 price76 price77 price78 price79 price80 price81 price82 price83 price84 price85 price86 price87 price88 price89 price90 price91 price92 price93 price94 price95 price96 price97 price98 price99 review { product { related { review 
{ product { related { price price1 price2 price3 price4 price5 price6 price7 price8 price9 price10 price11 price12 price13 price14 price15 price16 price17 price18 price19 price20 price21 price22 price23 price24 price25 price26 price27 price28 price29 price30 price31 price32 price33 price34 price35 price36 price37 price38 price39 price40 price41 price42 price43 price44 price45 price46 price47 price48 price49 price50 price51 price52 price53 price54 price55 price56 price57 price58 price59 price60 price61 price62 price63 price64 price65 price66 price67 price68 price69 price70 price71 price72 price73 price74 price75 price76 price77 price78 price79 price80 price81 price82 price83 price84 price85 price86 price87 price88 price89 price90 price91 price92 price93 price94 price95 price96 price97 price98 price99  } } 
} } } } } }
```
with hey and 200000 queries, 1000 concurrent clients, 1 core for the router (it saturates easily like this)

On main at 4617741:

```
Summary:                                                                                                                                
  Total:        120.8086 secs                                                                                                           
  Slowest:      10.8656 secs                                                                                                            
  Fastest:      0.0056 secs                                                                                                             
  Average:      0.5549 secs                                                                                                             
  Requests/sec: 1655.5115                                                                                                                                                                                                                           
                                                                                                                                   
Latency distribution:                                                                                                                   
  10% in 0.0445 secs                                                                                                                    
  25% in 0.0553 secs                                                                                                                    
  50% in 0.0739 secs                                                                                                                    
  75% in 0.0940 secs                                                                                                                    
  90% in 2.8722 secs                                                                                                                    
  95% in 3.0867 secs                                                                                                                    
  99% in 5.2827 secs    
```

This PR at bf9e5bb:

```
Summary:                                                          
  Total:        116.1452 secs                                     
  Slowest:      10.6822 secs                                      
  Fastest:      0.0053 secs                                       
  Average:      0.5313 secs                                       
  Requests/sec: 1721.9827                                         
                                                          
Latency distribution:                                             
  10% in 0.0427 secs                                              
  25% in 0.0533 secs                                              
  50% in 0.0711 secs                                              
  75% in 0.0908 secs                                              
  90% in 2.7576 secs                                              
  95% in 2.9643 secs                                              
  99% in 5.1863 secs
```

This PR at db4a518:

```
Summary:                                                              
  Total:        120.5513 secs                                         
  Slowest:      13.7664 secs                                          
  Fastest:      0.0062 secs                                           
  Average:      0.5552 secs                                           
  Requests/sec: 1659.0443                                             
                                                                
Latency distribution:                                                 
  10% in 0.0438 secs                                                  
  25% in 0.0550 secs                                                  
  50% in 0.0738 secs                                                  
  75% in 0.0941 secs                                                  
  90% in 2.9021 secs                                                  
  95% in 3.1246 secs                                                  
  99% in 5.1338 secs
```

So the results are inconclusive for now, but I see potential for improvement in the profiling traces

File: apollo-router-core/src/json_ext.rs (hunk 22 above)
Comment (cecton) [reply apollo-router-core/src/json_ext.rs:218]: 🦎

**Comment by BrynCooke** [comment]
Perf test please

**Comment by BrynCooke** [comment]
Perf tests rerun and available via the checks tab.
Possibly there is slight perf degradation, but would take several runs to confirm.

**Comment by Geal** [comment]
perf tests at 77ed25f: https://github.com/apollographql/router/pull/250/checks?check_run_id=4506815948
main 6993 rps vs PR 6109 rps so 12% perf regression

**Comment by Geal** [comment]
at ee50584: 5738rps so it's getting worse, I am reverting that last one

**Comment by Geal** [comment]
at 7f7de6c https://github.com/apollographql/router/pull/250/checks?check_run_id=4508772987:
6353rps so 9% perf regression.

I think I should stop there before I complicate the code too much. This is useful enough because it fixes #248 and opens up new designs. And I promise to make it up in other parts of the code, with variable deduplication #87 (that will not improve this particular benchmark though) or picking up one of the ideas in https://github.com/apollographql/router/issues/173

File: apollo-router-core/src/json_ext.rs (hunk 22 above)
Comment (Geal) [reply apollo-router-core/src/json_ext.rs]: I added a closure based visitor in 7f7de6c

File: apollo-router-core/src/json_ext.rs (hunk 21 above)
Comment (Geal) [reply apollo-router-core/src/json_ext.rs:153]: `Value::insert` was added in 9793f76

File: apollo-router-core/src/query_planner/mod.rs (hunk 13 above)
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs]: fixed in 533f09bfe361108807fc8812dd7f294a7816518a

File: apollo-router-core/src/json_ext.rs [hunk 24]
```diff
@@ -35,94 +26,30 @@ pub trait ValueExt {
...
+    /// Insert a `value` at a `Path`
+    #[track_caller]
+    fn insert(&mut self, path: &Path, value: Value) -> Result<(), FetchError>;
 
-        Ok(current)
-    }
+    /// Select all values matching a `Path`.
+    ///
+    /// this will return the values and their specific path in the `Value`:
+    /// a `Path` with a flatten node can match multiple values.
```
Comment (cecton) [inline apollo-router-core/src/json_ext.rs:45]: :yarn: This comment is outdated as this function doesn't return much.

File: apollo-router-core/src/json_ext.rs [hunk 25]
```diff
@@ -276,7 +426,7 @@ where
 /// This can be composed of strings and numbers
 #[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize, Default)]
 #[serde(transparent)]
-pub struct Path(Vec<PathElement>);
+pub struct Path(pub Vec<PathElement>);
```
Comment (cecton) [inline apollo-router-core/src/json_ext.rs:429]: I think we need to add `#[doc(hidden)]` on this and the `PathElement`.

File: apollo-router-core/src/query_planner/mod.rs [hunk 26]
```diff
@@ -200,8 +216,9 @@ impl PlanNode {
             Self::Sequence { nodes } | Self::Parallel { nodes } => {
                 Box::new(nodes.iter().flat_map(|x| x.service_usage()))
             }
-            Self::Fetch(fetch) => Box::new(vec![fetch.service_name.as_str()].into_iter()),
-            Self::Flatten(flatten) => Box::new(flatten.node.service_usage()),
+            Self::Fetch(fetch) => Box::new(Some(fetch.service_name()).into_iter()),
+
+            Self::Flatten(flatten) => flatten.node.service_usage(),
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:221]: :yarn: space consistency fix proposal

```suggestion
            Self::Fetch(fetch) => Box::new(Some(fetch.service_name()).into_iter()),
            Self::Flatten(flatten) => flatten.node.service_usage(),
```

File: apollo-router-core/src/query_planner/mod.rs [hunk 27]
```diff
@@ -253,66 +270,129 @@ impl PlanNode {
...
-    requires: Option<Vec<Selection>>,
+    use super::selection::{select_object, Selection};
+    use futures::StreamExt;
+    use serde::Deserialize;
+    use serde_json::{Map, Value};
+    use tracing::{instrument, Instrument};
 
-    /// The variables that are used for the subgraph fetch.
-    variable_usages: Vec<String>,
+    use crate::{FetchError, Object, Path, Request, Response, Schema, ServiceRegistry, ValueExt};
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:282]: :yarn: since the API is flat. I tend to use this everywhere so I don't have to maintain a list of imports.

```suggestion
    use crate::prelude::graphql::*;
```

File: apollo-router-core/src/query_planner/mod.rs [hunk 28]
```diff
@@ -253,66 +270,129 @@ impl PlanNode {
...
-    /// The name of the service or subgraph that the fetch is querying.
-    service_name: String,
+mod fetch {
+    use std::sync::Arc;
 
-    /// The data that is required for the subgraph fetch.
-    #[serde(skip_serializing_if = "Option::is_none")]
-    requires: Option<Vec<Selection>>,
+    use super::selection::{select_object, Selection};
+    use futures::StreamExt;
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:277]: :yarn: less important management this way
```suggestion
    use futures::prelude::*;
```

File: apollo-router-core/src/query_planner/mod.rs [hunk 29]
```diff
@@ -253,66 +270,129 @@ impl PlanNode {
...
+    use serde::Deserialize;
+    use serde_json::{Map, Value};
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:279]: :yarn: You probably don't need either of those. Value is re-exported by this crate and Object (alias for `Map<String, Value>`) is reexported too.

```suggestion
```

File: apollo-router-core/src/query_planner/mod.rs [hunk 30]
```diff
@@ -253,66 +270,129 @@ impl PlanNode {
...
+
+        /// The variables that are used for the subgraph fetch.
+        variable_usages: Vec<String>,
+
+        /// The GraphQL subquery that is used for the fetch.
+        operation: String,
+    }
+
+    struct Variables {
+        variables: Map<String, Value>,
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:303]: :yarn: 
```suggestion
        variables: Object,
```

File: apollo-router-core/src/query_planner/mod.rs [hunk 31]
```diff
@@ -253,66 +270,129 @@ impl PlanNode {
...
-            {
-                let response = response.lock().await;
-                tracing::trace!(
-                    "Creating representations at path '{}' for selections={:?} using data={}",
-                    current_dir,
-                    requires,
-                    serde_json::to_string(&response.data).unwrap(),
+        /// The data that is required for the subgraph fetch.
+        #[serde(skip_serializing_if = "Option::is_none")]
+        requires: Option<Vec<Selection>>,
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:293]: :yarn: Probably an unneeded option again. Check this out to see how to remove it: https://github.com/apollographql/router/pull/257/files

Those unneeded option were just there for the parsing but they make the actual code more complicated.

File: apollo-router-core/src/query_planner/mod.rs [hunk 32]
```diff
@@ -253,66 +270,129 @@ impl PlanNode {
...
+    }
+
+    impl Variables {
+        fn new<'a>(
+            requires: Option<&Vec<Selection>>,
+            variable_usages: &[String],
+            data: &Value,
+            current_dir: &'a Path,
+            request: &Arc<Request>,
+            schema: &Arc<Schema>,
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:314]: :yarn: 
```suggestion
            request: &Request,
            schema: &Schema,
```

File: apollo-router-core/src/query_planner/mod.rs [hunk 33]
```diff
@@ -253,66 +270,129 @@ impl PlanNode {
...
+    }
+
+    impl FetchNode {
+        pub(crate) async fn fetch_node<'a>(
+            &'a self,
+            data: &'a Value,
+            current_dir: &'a Path,
+            request: &'a Arc<Request>,
+            service_registry: Arc<dyn ServiceRegistry>,
+            schema: &'a Arc<Schema>,
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:374]: :yarn: Either you pass an `Arc<Something>` (because you need to clone), either you pass a `&Something`. But `&Arc<Something>` is unnecessary and restrict the way the caller can use this function.

```suggestion
            request: &'a Request,
            service_registry: Arc<dyn ServiceRegistry>,
            schema: &'a Schema,
```

File: apollo-router-core/src/query_planner/mod.rs [hunk 34]
```diff
@@ -253,66 +270,129 @@ impl PlanNode {
...
+        variables: Map<String, Value>,
+        paths: Vec<Path>,
+    }
+
+    impl Variables {
+        fn new<'a>(
+            requires: Option<&Vec<Selection>>,
+            variable_usages: &[String],
+            data: &Value,
+            current_dir: &'a Path,
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:312]: :yarn: 
```suggestion
        fn new(
            requires: Option<&Vec<Selection>>,
            variable_usages: &[String],
            data: &Value,
            current_dir: &Path,
```

File: apollo-router-core/src/query_planner/mod.rs [hunk 35]
```diff
@@ -253,66 +270,129 @@ impl PlanNode {
...
+                        })
+                        .collect::<Object>(),
+                    paths: Vec::new(),
+                })
             }
+        }
+    }
+
+    impl FetchNode {
+        pub(crate) async fn fetch_node<'a>(
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:368]: :yarn: This lifetime looks unnecessary.

I think it's only used to make self life as long as current_dir. All the rest can use anonymous lifetime.

File: apollo-router-core/src/query_planner/mod.rs [hunk 36]
```diff
@@ -253,66 +270,129 @@ impl PlanNode {
...
+        ) -> Result<Variables, FetchError> {
+            if let Some(requires) = requires {
+                let mut variables = Object::with_capacity(1 + variable_usages.len());
+                variables.extend(variable_usages.iter().filter_map(|key| {
+                    request.variables.as_ref().map(|v| {
+                        v.get(key)
+                            .map(|value| (key.clone(), value.clone()))
+                            .unwrap_or_default()
+                    })
+                }));
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:324]: :yarn: 
```suggestion
                let variables = variable_usages
                    .iter()
                    .filter_map(|key| {
                        request.variables.as_ref().map(|v| {
                            v.get(key)
                                .map(|value| (key.clone(), value.clone()))
                                .unwrap_or_default()
                        })
                    }))
                    .collect::<Object>();
```

**Review by garypen — APPROVED** [review]
One very ignorable comment.

File: apollo-router-core/src/query_planner/mod.rs (hunk 36 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:324]: I tried that while doing the PR, but apparently not using with_capacity will have a performance impact (because it could trigger a reallocation when adding the last element)

Comment (cecton) [reply apollo-router-core/src/query_planner/mod.rs:322]: Oh I missed the `+ 1` sorry. You're :100:

File: apollo-router-core/src/query_planner/mod.rs (hunk 35 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:366]: Any attempt at making one of the lifetimes anonymous results in the following error:

```
   Compiling apollo-router-core v0.1.0-alpha.2 (/home/geal/dev/router/apollo-router-core)
error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
   --> apollo-router-core/src/query_planner/mod.rs:374:14
    |
374 |         ) -> Result<Value, FetchError> {
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: hidden type `impl futures::Future` captures lifetime smaller than the function body
   --> apollo-router-core/src/query_planner/mod.rs:374:14
    |
374 |         ) -> Result<Value, FetchError> {
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0700`.
```

File: apollo-router-core/src/json_ext.rs (hunk 24 above)
Comment (Geal) [reply apollo-router-core/src/json_ext.rs]: fixed in 1e5489c

File: apollo-router-core/src/json_ext.rs (hunk 25 above)
Comment (Geal) [reply apollo-router-core/src/json_ext.rs:425]: fixed in 1e5489c

File: apollo-router-core/src/query_planner/mod.rs (hunk 32 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs]: fixed in 634b640

File: apollo-router-core/src/query_planner/mod.rs (hunk 33 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs]: fixed in 634b640

File: apollo-router-core/src/json_ext.rs [hunk 37]
```diff
@@ -212,6 +148,220 @@ impl ValueExt for Value {
...
+
+    #[track_caller]
+    fn select_values_and_paths<'a, F>(&'a self, path: &'a Path, mut f: F) -> Result<(), FetchError>
+    where
+        F: FnMut(Path, &'a Value),
+    {
+        match iterate_path(&Path::default(), &path.0, self, &mut f) {
+            Some(err) => Err(err),
+            None => Ok(()),
+        }
```
[the remark this answers is not in the document]
Comment (Geal) [reply apollo-router-core/src/json_ext.rs]: right, I forgot to change that, that was not nice to look at. Fixed in 60ac12a

**Comment by Geal** [comment]
we're at 7368rps (main) VS 7014rps (this PR) so it's in good shape right now. I suspect replacing those `Option<Vec<T>>` with `Vec<T>` has a good impact

File: apollo-router-core/src/query_planner/mod.rs (hunk 35 above)
Comment (cecton) [reply apollo-router-core/src/query_planner/mod.rs:365]: lifetimes are hard xD

File: apollo-router-core/src/query_planner/mod.rs (hunk 31 above)
Comment (cecton) [reply apollo-router-core/src/query_planner/mod.rs]: yes... it happens when the code drives the developer's choices. Now my eyes are trained to see that (very) recurring pattern with serde and structopt

**Comment by cecton** [comment]
> we're at 7368rps (main) VS 7014rps (this PR) so it's in good shape right now. I suspect replacing those `Option<Vec<T>>` with `Vec<T>` has a good impact

that also was unintentional :sweat_smile:

File: apollo-router-core/src/query_planner/mod.rs [hunk 38]
```diff
@@ -4,10 +4,9 @@ mod selection;
 
 use crate::prelude::graphql::*;
 pub use caching_query_planner::*;
-use futures::lock::Mutex;
 use futures::prelude::*;
+use futures::stream::FuturesUnordered;
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:8]: :yarn: you already have it more or less in scope. Use `stream::FuturesUnordered` in your code.

```suggestion
```

File: apollo-router-core/src/query_planner/mod.rs [hunk 39]
```diff
@@ -79,103 +78,120 @@ impl QueryPlan {
...
                 }
                 PlanNode::Parallel { nodes } => {
-                    future::join_all(nodes.iter().map(|plan| {
-                        plan.execute_recursively(
-                            Arc::clone(&response),
-                            current_dir,
+                    value = Value::default();
+                    async {
+                        {
+                            let mut stream: FuturesUnordered<_> = nodes
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:134]: :information_source: already in scope by future's prelude

```suggestion
                            let mut stream: stream::FuturesUnordered<_> = nodes
```

File: apollo-router-core/src/query_planner/mod.rs [hunk 40]
```diff
@@ -79,103 +78,120 @@ impl QueryPlan {
...
 }
 
 impl PlanNode {
     fn execute_recursively<'a>(
         &'a self,
-        response: Arc<Mutex<Response>>,
         current_dir: &'a Path,
         request: Arc<Request>,
         service_registry: Arc<dyn ServiceRegistry>,
         schema: Arc<Schema>,
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:104]: :yarn: I wonder if you actually need those arcs... :thinking: 
```suggestion
        request: &Request,
        service_registry: Arc<dyn ServiceRegistry>,
        schema: &Schema,
```

The one for the service registry could be replace by `&impl ServiceRegistry` I believe :thinking: 

:information_source: the good point about not using arcs in argument like that: you can pass a non-arc object or an arc one :brain: (so it's more flexible)

Comment (cecton) [reply apollo-router-core/src/query_planner/mod.rs:104]: Wait... could that also have perf impact? Because we're less incrementing the arf ref counter?

File: apollo-router-core/src/query_planner/mod.rs [hunk 41]
```diff
@@ -253,65 +269,127 @@ impl PlanNode {
...
+                let mut variables = Object::with_capacity(1 + variable_usages.len());
+                variables.extend(variable_usages.iter().filter_map(|key| {
+                    request
+                        .variables
+                        .get(key)
+                        .map(|value| (key.clone(), value.clone()))
+                }));
+
+                let mut paths = Vec::new();
+                let mut values = Vec::new();
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:325]: :grey_question: Do we know the maximum number of values that could go into those vec? Because then we can allocate once for the maximum capacity. It's probably a bit of wasted space but will reduce the number of allocations and we might gain some perf improvement

File: apollo-router-core/src/query_planner/mod.rs [hunk 42]
```diff
@@ -325,116 +403,68 @@ impl FetchNode {
...
-                                return Err(FetchError::ExecutionInvalidContent {
-                                    reason: "Received invalid type for key `_entities`!"
-                                        .to_string(),
-                                });
+            };
+
+            self.response_at_path(current_dir, paths, subgraph_response)
+        }
+
+        #[instrument(, level = "trace", name = "response_insert", skip_all)]
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:423]: :yarn: 
```suggestion
        #[instrument(level = "trace", name = "response_insert", skip_all)]
```

File: apollo-router-core/src/query_planner/mod.rs [hunk 43]
```diff
@@ -325,116 +403,68 @@ impl FetchNode {
...
+                // because we need to take ownership of the inner value
+                if let Value::Object(mut map) = data {
+                    if let Some(entities) = map.remove("_entities") {
+                        tracing::trace!("Received entities: {:?}", &entities);
+
+                        if let Value::Array(array) = entities {
+                            let mut value = Value::default();
+
+                            for (entity, path) in array.into_iter().zip(paths.into_iter()) {
+                                value.insert(&path, entity)?;
```
Comment (cecton) [inline apollo-router-core/src/query_planner/mod.rs:443]: :grey_question: I wonder if we would reduce the number of allocation by making this method takes an owned path :thinking: so you can move the value in it instead of passing it by reference. It gets cloned/copied in there anyway

**Review by cecton — APPROVED** [review]

File: apollo-router-core/src/query_planner/selection.rs [hunk 44]
```diff
@@ -146,6 +117,32 @@ mod tests {
...
+
+        Ok(Value::Array(
+            values
+                .into_iter()
+                .flat_map(|value| match (value, selections) {
+                    (Value::Object(content), requires) => {
+                        select_object(content, requires, schema).transpose()
+                    }
+                    (_, _) => Some(Err(FetchError::ExecutionInvalidContent {
+                        reason: "not an object".to_string(),
```
Comment (o0Ignition0o) [inline apollo-router-core/src/query_planner/selection.rs:139]: ❓  it looks like we always have &'static str for ExecutionInvalidContent

Comment (cecton) [reply apollo-router-core/src/query_planner/selection.rs:139]: Unfortunately this type (`FetchError`) is public and should be kept generic. There are a lot of reasons -no pun intended- why we would want to have a `String` for the field `reason`.

Though.... :thinking: One valid alternative would be a `Cow<'static, str>`. This can improve performance if that error happens a lot.

File: apollo-router-core/src/query_planner/mod.rs (hunk 43 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:443]: the path is not copied in `insert`, it takes it as reference and iterates over the `PathElement`, so there's no cloning. It's the  `iterate_path` (and `ValueExt::select_values_and_paths`) that allocate paths, and there I went with a reference so a path can be reused in multiple calls, and we do not need to allocate paths for nothing if we do not select any value in the end.
I suspect there will be ways to optimize it further :)

File: apollo-router-core/src/query_planner/mod.rs (hunk 40 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs]: for `Request` and `Schema`, done in 2c433c0, no issue. For `ServiceRegistry`, it's a bit trickier, with `&impl` it complains that the type is not `Sized` (well, yeah), I'll try by using `dyn` instead (since in most cases it will be a `dyn` anyway

File: apollo-router-core/src/query_planner/selection.rs (hunk 44 above)
Comment (o0Ignition0o) [reply apollo-router-core/src/query_planner/selection.rs:139]: Hmm indeed, I don't think we want to optimize that yet, errors shouldn't happen that much should they ?

File: apollo-router-core/src/query_planner/mod.rs (hunk 40 above)
Comment (cecton) [reply apollo-router-core/src/query_planner/mod.rs]: Have you tried adding `+ Sized` to the trait?

File: apollo-router-core/src/query_planner/mod.rs (hunk 41 above)
Comment (cecton) [reply apollo-router-core/src/query_planner/mod.rs:312]: probably the visitor actually knows :thinking: too complicated to implement for now, we would need to go back to an iterator also I believe so never mind. Unless we see a big perf hit here I don't see the value

File: apollo-router-core/src/query_planner/mod.rs (hunk 40 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs]: for `ServiceRegistry`: a694c5e 
It looks fine so far, but it forces a trait object as argument

File: apollo-router-core/src/query_planner/mod.rs (hunk 43 above)
Comment (cecton) [reply apollo-router-core/src/query_planner/mod.rs:430]: Yes sorry I meant insert takes a reference, then in `insert` it's maching over reference, then it either copying (if it's an index, usize) or cloning (key, string, to_string). Therefore, since here you're already dropping the `path` in this loop, you can pass ownership of `path` to `insert` and avoid the cloning of the key string.

File: apollo-router-core/src/query_planner/selection.rs (hunk 44 above)
Comment (cecton) [reply apollo-router-core/src/query_planner/selection.rs:139]: yeah well... not a big deal to change either so :woman_shrugging:

File: apollo-router-core/src/query_planner/mod.rs (hunk 40 above)
Comment (cecton) [reply apollo-router-core/src/query_planner/mod.rs]: looks cool

File: apollo-router-core/src/query_planner/mod.rs (hunk 41 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:312]: yup I think we can explore the iterator approach later (spoiler alert: I tried, it's annoying because of the `PathElement` enum different behaviours, and I really wish generators were in stable)

File: apollo-router-core/src/query_planner/mod.rs (hunk 43 above)
Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:430]: oh, I see, yes I'll fix that

Comment (cecton) [reply apollo-router-core/src/query_planner/mod.rs:430]: (I might be wrong)

Comment (Geal) [reply apollo-router-core/src/query_planner/mod.rs:389]: ok so if the `Path` is owned, we can avoid the `to_string()` here: https://github.com/apollographql/router/pull/250/files#diff-ee3d76610144cb4b3cfde4d8870c3022107caf2850413af0321a6336ee23c342R262
we would still need to clone the key to have it available here: https://github.com/apollographql/router/pull/250/files#diff-ee3d76610144cb4b3cfde4d8870c3022107caf2850413af0321a6336ee23c342R268
because we need to set the current node before looking up the key again. So there's no gain there :disappointed:

**Comment by Geal** [comment]
Thanks all for helping me on this PR!
