### PR TITLE
fix(context): change context methods about extensions to avoid deadlock

### LINKED ISSUE #476: The implementation of `.extensions()` and `.extensions_mut()` could easily deadlock
After reading the implementation of `extensions` on `Context` I think it's not a good practice to directly return `RwWriteLockGuard` and `RwReadLockGuard` because it hides the fact we're using a `RwLock` on extensions. Then just by writing this :+1: 

```rust
let extensions = context.extensions().await;
let mut_extensions = context.extensions_mut().await;
```

we just created a deadlock. I think we should only expose functions to `add`, `remove`, `get` a specific item in the extensions to avoid this behavior. And never return a `RwLockGuard`

### PR DESCRIPTION
**Pull request by bnjjj**
resolves #476

Renamed `extensions()` and `extensions_mut()` with a prefix `lock_` to let users know they are locking the resources
Add common methods to context for extensions to avoid as much as possible to use `lock_extensions()` and `lock_extensions_mut()`

### CODE REVIEW

File: apollo-router-core/src/context.rs [hunk 1]
```diff
@@ -44,13 +46,51 @@ impl From<Context<http_compat::Request<Request>>> for Context<Arc<http_compat::R
...
+    }
+
+    /// Inserts a key-value pair into extensions.
+    /// If extensions did not have this key present, None is returned.
+    /// If extensions did have this key present, the value is updated, and the old value is returned.
+    pub async fn insert_extension(&self, k: String, v: Value) -> Option<Value> {
+        self.extensions.write().await.insert(k, v)
+    }
+
+    /// Inserts a key-value pair into extensions.
```
Comment (Geal) [inline apollo-router-core/src/context.rs:84]:
```suggestion
    /// Removes a key-value pair from extensions.
```

**Review by o0Ignition0o — APPROVED** [review]

**Review by o0Ignition0o — APPROVED** [review]

File: apollo-router-core/src/context.rs [hunk 2]
```diff
@@ -44,13 +46,59 @@ impl From<Context<http_compat::Request<Request>>> for Context<Arc<http_compat::R
...
+    pub fn lock_extensions(&self) -> impl Future<Output = RwLockReadGuard<Object>> {
         self.extensions.read()
     }
 
-    pub fn extensions_mut(&self) -> impl Future<Output = RwLockWriteGuard<Object>> {
+    /// Take a write lock of extensions
+    /// Be careful when using this method, you could create deadlock if you use `lock_extensions` in the same scope
+    pub fn lock_extensions_mut(&self) -> impl Future<Output = RwLockWriteGuard<Object>> {
         self.extensions.write()
     }
```
Comment (garypen) [inline apollo-router-core/src/context.rs:59]: Can we consider going further and remove these two functions completely?

Comment (bnjjj) [reply apollo-router-core/src/context.rs:59]: I'm not sure TBH. Maybe sometimes people will need to play with IterMut or Iter or something equivalent. Will ask tomorrow during the huddle if someone have thoughts
