### PR TITLE
fix dev mode with configuration validation

### LINKED ISSUE #1811: Change the way we enable dev mode in configuration to validate changes
Possibly in the constructor here before the call to `validate`: https://github.com/apollographql/router/blob/main/apollo-router/src/configuration/mod.rs#L260

Then we can get rid of the multiple times this is called in ConfigurationSource.
Also it means that dev mode is set up before validation takes place. Setting it after means we potentially miss validation errors that could be caused by the activation of dev mode.

_Originally posted by @BrynCooke in https://github.com/apollographql/router/pull/1808#discussion_r972747844_

### PR DESCRIPTION
**Pull request by bnjjj**
close #1811 

I changed the way we watched file changes. When we launch the file watching it automatically triggers a first event, so before we were reading the configuration twice. Now only once. 

I had to introduce `serial_test` crate to force 2 tests for dev mode to be ran in serial, because it needs to check the environment variable. It's a temporary fix to let me test it and be ready for the release. But I will find another solution in the future

### CODE REVIEW

File: apollo-router/src/configuration/mod.rs [hunk 1]
```diff
@@ -241,9 +238,8 @@ impl Configuration {
         cors: Option<Cors>,
         plugins: Map<String, Value>,
         apollo_plugins: Map<String, Value>,
-        dev: Option<bool>,
```
Comment (BrynCooke) [inline apollo-router/src/configuration/mod.rs:244]: Suggest leaving the dev option on the builder. Then you can avoid modifying the env variable in your test.

**Review by BrynCooke — CHANGES_REQUESTED** [review]

File: apollo-router/src/configuration/mod.rs (hunk 1 above)
Comment (bnjjj) [reply apollo-router/src/configuration/mod.rs:244]: It won't fix the issue with en variables in my tests. Because I provide a yaml file and then it's directly deserialized. I don't use the builder

File: apollo-router/src/executable.rs [hunk 2]
```diff
@@ -50,7 +52,12 @@ pub(crate) struct Opt {
     log_level: String,
 
     /// Reload configuration and schema files automatically.
-    #[clap(alias = "hr", long = "hot-reload", env = "APOLLO_ROUTER_HOT_RELOAD")]
+    #[clap(
+        alias = "hr",
+        long = "hot-reload",
+        env = "APOLLO_ROUTER_HOT_RELOAD",
```
Comment (garypen) [inline apollo-router/src/executable.rs:58]: Are these new environment variables? If so, do we want/need to document them?

**Review by garypen — APPROVED** [review]

File: apollo-router/src/executable.rs (hunk 2 above)
Comment (bnjjj) [reply apollo-router/src/executable.rs:58]: It's not new ones, I just added a parameter to clap to correctly parse it under the hood

File: apollo-router/src/configuration/mod.rs (hunk 1 above)
Comment (bnjjj) [reply apollo-router/src/configuration/mod.rs:244]: Fixed

**Review by BrynCooke — APPROVED** [review]
