### PR TITLE
Unify external config defaulting

### LINKED ISSUE #2404: `experimental_response_trace_id` issues
A couple of related issues:

**Number one**
With version 1.8, if I configure the router with:

```yaml
telemetry:
  apollo:
    field_level_instrumentation_sampler: always_on
  tracing:
    experimental_response_trace_id:
      enabled: true
```

The router fails to start with: 

```
ERROR apollo_router::router_factory: plugin apollo.telemetry could not be configured: missing field `header_name`
```

(I was trying to get `apollo-trace-id` to appear in the trace inspector in Studio. If I set a custom header name, it works

**Number two**
If I enable `--dev` mode with the same configuration, using debug logs the resolved configuration has a null `header_name`: 

```
  "tracing": {
    "experimental_response_trace_id": {
      "enabled": true,
      "header_name": null
    }
  },
```

I would expect that `--dev` mode would override `experimental_response_trace_id.enabled` to true, but leave any existing `header_name` alone.

### PR DESCRIPTION
**Pull request by BrynCooke**
Fixes #2404 #2481

Moves defaulting logic from hard coded section in config init to a central location that uses transformers.

Previously `dev` mode was operating against the configuration object model. This meant that it would sometimes replace pieces of configuration where really it should just have modified it. Now dev mode will override the following in the yaml config, but it will leave any adjacent configuration as it was:

```yaml
homepage:
  enabled: false
include_subgraph_errors:
  all: true
plugins:
  experimental.expose_query_plan: true
sandbox:
  enabled: true
supergraph:
  introspection: true
telemetry:
  tracing:
    experimental_response_trace_id:
      enabled: true
```

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [x] Changes are compatible[^1]
- [ ] ~~Documentation[^2] completed~~
- [ ] ~~Performance impact assessed and acceptable~~
- Tests added and passing[^3]
    - [x] Unit Tests
    - [ ] ~~Integration Tests~~
    - [x] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

### CODE REVIEW

File: apollo-router/src/configuration/expansion.rs [hunk 1]
```diff
@@ -43,6 +45,16 @@ impl Expansion {
             .split(',')
             .map(|mode| mode.trim().to_string())
             .collect::<Vec<String>>();
+
+        let dev_mode_defaults = if std::env::var(APOLLO_ROUTER_DEV_ENV).ok().as_deref()
+            == Some("true")
+        {
+            tracing::info!("Running with *development* mode settings which facilitate development experience (e.g., introspection enabled)");
```
Comment (o0Ignition0o) [inline apollo-router/src/configuration/expansion.rs:52]: should we link to a router docs "dev-mode" section?

File: apollo-router/src/configuration/expansion.rs [hunk 2]
```diff
@@ -98,31 +147,46 @@ impl Expansion {
...
+            if default.env_name.is_some()
+                && !jsonpath_lib::select(config, &format!("$.{}", default.config_path))
+                    .unwrap_or_default()
+                    .is_empty()
             {
+                // Env variables do NOT override config. If the user want to enable this then they must use config expansion.
+                continue;
+            }
+
+            if default.quote {
```
Comment (o0Ignition0o) [inline apollo-router/src/configuration/expansion.rs:182]: I don't understand what `quote` is and what it represents/does :/

**Review by o0Ignition0o — COMMENTED** [review]
LGTM overall, I'll approve if you explain / document `quote` because I don't quite get it (maybe it needs to be renamed?).

File: apollo-router/src/configuration/expansion.rs (hunk 2 above)
Comment (BrynCooke) [reply apollo-router/src/configuration/expansion.rs]: I had a better idea in the end [8901a4a](https://github.com/apollographql/router/pull/2490/commits/8901a4a7176a2019c09d38c21d36ab74bfb14144)

Buildstructor gives us nice Into methods, so instead of quoting we can try and coerce env variables into the desired type. If it fails then it falls back to string.

File: apollo-router/src/configuration/expansion.rs (hunk 1 above)
Comment (BrynCooke) [reply apollo-router/src/configuration/expansion.rs:54]: Good idea, but out of scope for this PR. We would need a stable URL set up.

**Review by o0Ignition0o — APPROVED** [review]
