### PR TITLE
fix fragments on queries

### LINKED ISSUE #1290: Query including fragments return null
**Describe the bug**
We have a query using fragments
```
{
  ...ShoppingListFragmentTest
}

fragment ShoppingListFragmentTest on ShoppingListQueryInterface {
shoppingLists {
  results {
    id
  }
  total
}
```
the router returns data:null for it, although the sub-service returns a valid non-null response. We are assuming that there is an issue in assembling the response. The query plan for the query is:
```
query plan is: QueryPlan {
   usage_reporting: UsageReporting { 
 	stats_report_key: "# -\nfragment ShoppingListFragmentTest on ShoppingListQueryInterface{shoppingLists{results{id}total {...ShoppingListFragmentTest}", 
        referenced_fields_by_type: {
           "ShoppingListQueryInterface": ReferencedFieldsForType { field_names: ["shoppingLists"], is_interface: true }, 
           "ShoppingListQueryResult": ReferencedFieldsForType { field_names: ["results", "total"], is_interface: false },            
           "ShoppingList": ReferencedFieldsForType { field_names: ["id"], is_interface: false }
        } 
    },
     root: Fetch(FetchNode { service_name: "sphere", requires: [], variable_usages: [], operation: "{shoppingLists{results{id}total}}", operation_name: None, operation_kind: Query }) }
```

**Expected behavior**
router should be able to assemble the response and return non-null data.

### PR DESCRIPTION
**Pull request by Geal**
Fix #1290

The `schema` object can specify objects for queries, mutations or subscriptions that are not named `Query`, Mutation` or `Subscription`. This must be supported in response formatting

### CODE REVIEW

File: apollo-router/src/spec/query.rs [hunk 1]
```diff
@@ -569,14 +566,23 @@ impl Query {
...
                     if let Some(fragment) = self.fragments.get(name) {
-                        // top level objects will not provide a __typename field
-                        match (fragment.type_condition.as_str(), operation.kind) {
-                            ("Query", OperationKind::Query)
-                            | ("Mutation", OperationKind::Mutation) => {}
-                            _ => {
-                                return Err(InvalidValue);
+                        let operation_type_name = schema.root_operation_name(operation.kind);
+                        let is_apply = {
+                            // First determine if the fragment is for zn interface
```
Comment (bnjjj) [inline apollo-router/src/spec/query.rs:571]:
```suggestion
                            // First determine if the fragment is for an interface
```
