### PR TITLE
make sure the compression state is flushed

### LINKED ISSUE #3035: Responses getting cut off in v1.16.0
**Describe the bug**
There seems to be a major bug in v1.16.0. It looks like responses are getting cutt-off mid json string. Not using `@defer` or anything of such kind.

It seems to happen when the `Accept-Encoding` header is present (which is sent by all browsers by default).

**To Reproduce**
1. Do a query that returns a long response
2. Send `Accept-Encoding: gzip` header

**Expected behavior**
Returns valid JSON

**Output**
JSON that is cutt-off at some length, resulting in an invalid data/JSON being returned.

### PR DESCRIPTION
**Pull request by Geal**
Fix #3035

In some cases, the "finish" call to flush the compression state at the end does not flush th entire state, so it has to be called multiple times.

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [x] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [x] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

### CODE REVIEW

**Comment by BrynCooke** [comment]
Is it possible to have a test?

**Review by bnjjj — APPROVED** [review]

File: apollo-router/src/axum_factory/compression/mod.rs [hunk 1]
```diff
@@ -123,19 +124,25 @@ where {
...
+                    Err(e) => {
+                        let _ = tx.send(Err(e.into())).await;
+                        break;
+                    }
+                    Ok(is_flushed) => {
+                        let len = partial_output.written().len();
+
+                        let mut buf = partial_output.into_inner();
+                        buf.resize(len, 0);
+                        let _ = tx.send(Ok(buf.freeze())).await;
```
Comment (bnjjj) [inline apollo-router/src/axum_factory/compression/mod.rs:141]: Maybe break if there is an error here

**Comment by Geal** [comment]
I'm working on adding a test

File: apollo-router/src/axum_factory/compression/mod.rs [hunk 2]
```diff
@@ -79,7 +79,8 @@ where {
                         }
                     }
                     Ok(data) => {
-                        let mut buf = BytesMut::zeroed(1024);
+                        // most compression algorithms have a compression ratio of more than 90% for JSON
+                        let mut buf = BytesMut::zeroed(data.len() / 10);
```
Comment (garypen) [inline apollo-router/src/axum_factory/compression/mod.rs:83]: Not this change, but does it need to be zeroed or could we just create `with_capacity()`?

File: apollo-router/src/axum_factory/compression/mod.rs [hunk 3]
```diff
@@ -123,19 +124,25 @@ where {
...
-                Err(e) => {
-                    let _ = tx.send(Err(e.into())).await;
-                }
-                Ok(_) => {
-                    let len = partial_output.written().len();
-
-                    let mut buf = partial_output.into_inner();
-                    buf.resize(len, 0);
-                    let _ = tx.send(Ok(buf.freeze())).await;
+                match self.finish(&mut partial_output) {
```
Comment (garypen) [inline apollo-router/src/axum_factory/compression/mod.rs:131]: I looked at [the docs](https://docs.rs/flate2/1.0.26/flate2/write/struct.ZlibDecoder.html#method.finish) for `flate2`. The note suggests that we maybe shouldn't be using finish where the underlying stream of data is async.

Does that comment apply to us?

File: apollo-router/src/axum_factory/compression/mod.rs (hunk 2 above)
Comment (Geal) [reply apollo-router/src/axum_factory/compression/mod.rs:83]: the compressor has to write into a mutable slice, it has to be initialized. I could take a look at MaybeUninit here, but I don't think the PartialBuffer type is set up for it

File: apollo-router/src/axum_factory/compression/mod.rs (hunk 3 above)
Comment (Geal) [reply apollo-router/src/axum_factory/compression/mod.rs:131]: here we know that there will be no more data after that because the stream has closed, so we can call finish

File: apollo-router/src/axum_factory/compression/mod.rs (hunk 1 above)
Comment (Geal) [reply apollo-router/src/axum_factory/compression/mod.rs]: fixed in [7a8eda9](https://github.com/apollographql/router/pull/3037/commits/7a8eda97f89d6de41499066a118152f3ff521a98)

**Comment by Geal** [comment]
@BrynCooke I added a test in [16da0e4](https://github.com/apollographql/router/pull/3037/commits/16da0e4bf7edaeea5f864c464e17f3c4bcaf0e8f). I validated that it would have caught the bug

**Review by garypen — APPROVED** [review]

File: .changesets/fix_geal_fix_compression_finish.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+### make sure the compression state is flushed ([Issue #3035](https://github.com/apollographql/router/issues/3035))
+
+In some cases, the "finish" call to flush the compression state at the end does not flush th entire state, so it has to be called multiple times.
+
+By [@Geal](https://github.com/Geal) in https://github.com/apollographql/router/pull/3037
```
Comment (abernix) [inline .changesets/fix_geal_fix_compression_finish.md:5]: I would suggest calling out that this was a regression introduced in 1.16.0 and linking to the issue/PR that introduced it — for posterity — and so folks immediately recognize that 1.16.0 has its limitations.

File: .changesets/fix_geal_fix_compression_finish.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+### make sure the compression state is flushed ([Issue #3035](https://github.com/apollographql/router/issues/3035))
+
+In some cases, the "finish" call to flush the compression state at the end does not flush th entire state, so it has to be called multiple times.
```
Comment (garypen) [inline .changesets/fix_geal_fix_compression_finish.md:3]: NIT:
```suggestion
In some cases, the "finish" call to flush the compression state at the end does not flush the entire state, so it has to be called multiple times.
```

**Review by garypen — APPROVED** [review]

**Review by bnjjj — APPROVED** [review]

File: .changesets/fix_geal_fix_compression_finish.md [hunk 6]
```diff
@@ -0,0 +1,5 @@
+### make sure the compression state is flushed ([Issue #3035](https://github.com/apollographql/router/issues/3035))
+
+In some cases, the "finish" call to flush the compression state at the end does not flush the entire state, so it has to be called multiple times.
```
Comment (Geal) [inline .changesets/fix_geal_fix_compression_finish.md:3]:
```suggestion
In some cases, the "finish" call to flush the compression state at the end does not flush the entire state, so it has to be called multiple times.

This fixes a regression introduced in 1.16.0 by [#2986](https://github.com/apollographql/router/pull/2986) where large responses would be cut short when compressed.
```
