### PR TITLE
fix(telemetry): support more types for metric counters

### LINKED ISSUE #3865: Panic in DEBUG when using the wrong type with metrics macros and MetricsLayer
```
tracing::info!(
            monotonic_counter
                .apollo
                .router
                .operations
                .authentication
                .jwt = 1,
            authentication.jwt.failed = true
        )
```

it breaks because you must specify the type lie `= 1u64`

### PR DESCRIPTION
**Pull request by bnjjj**
Add more supported types for metric counters in `MetricsLayer`.

Now it's not mandatory and won't panic in debug mode if you don't specify `1u64` in this example:

```rust
tracing::info!(
    monotonic_counter
        .apollo
        .router
        .operations
        .authentication
        .jwt = 1,
    authentication.jwt.failed = true
)
```

Fixes #3865 

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [x] Changes are compatible[^1]
- [x] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [x] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

### CODE REVIEW

**Review by Geal — APPROVED** [review]

**Review by BrynCooke — APPROVED** [review]

File: apollo-router/src/plugins/telemetry/metrics/layer.rs [hunk 1]
```diff
@@ -26,7 +26,7 @@ use super::METRIC_PREFIX_VALUE;
 
 macro_rules! log_and_panic_in_debug_build {
     ($($tokens:tt)+) => {{
-        tracing::debug!($($tokens)+);
+        tracing::error!($($tokens)+);
```
Comment (BrynCooke) [inline apollo-router/src/plugins/telemetry/metrics/layer.rs:29]: Note that this does mean there is the potential to spam logs if they have their attributes incorrect.

Comment (bnjjj) [reply apollo-router/src/plugins/telemetry/metrics/layer.rs:29]: Yes, but for now it's completely invisible. I'm tempted to put this either as a warn or error but it should be louder than today because it's discarded. What do you think ?
