### PR TITLE
parse OTLP endpoint address

### LINKED ISSUE #149: Open Telemetry with tonic panics if configured with an endpoint address without scheme
**Describe the bug**

A [router config](https://github.com/apollographql/supergraph-demo-fed2/blob/main/router/configuration.yaml#L17) with otel tracing set to use Grpc with an endpoint of `collector:4317` and [Grpc enabled in the collector-config.yaml](https://github.com/apollographql/supergraph-demo-fed2/blob/main/opentelemetry/collector-config.yml#L4) generates the following error:

```
apollo-router  | Nov 16 14:04:59.859 ERROR apollo_router: OpenTelemetry trace error occurred: Exporter otlp encountered the following error(s): the grpc server returns error Unknown error
```

**To Reproduce**
1. `git clone git@github.com:apollographql/supergraph-demo-fed2.git`
2. `make docker-up-router-otel` - uses [docker-compose.router-otel.yml](https://github.com/apollographql/supergraph-demo-fed2/blob/main/docker-compose.router-otel.yml)
3. `make query`
4. `docker compose -f ./docker-compose.router.yml logs apollo-router`
5. see error above

**Expected behavior**
The router to work like the Gateway with the same otel config like https://github.com/apollographql/supergraph-demo-fed2#tracing-with-open-telemetry which does [essentially the same thing but using the Gateway](https://github.com/apollographql/supergraph-demo-fed2/blob/main/docker-compose.otel-collector.yml) instead of the router.

One difference is that the Gateway config uses `CollectorTraceExporter` with a url of `http://${host}:${collectorPort}/v1/trace`. 

The [router config](https://github.com/apollographql/supergraph-demo-fed2/blob/main/router/configuration.yaml#L17) is using Grpc with an endpoint of `collector:4317`, not localhost. [Grpc is enabled in the collector-config.yaml](https://github.com/apollographql/supergraph-demo-fed2/blob/main/opentelemetry/collector-config.yml#L4) so not sure what is going on.

**Output**
```
apollo-router  | Nov 16 14:04:59.859 ERROR apollo_router: OpenTelemetry trace error occurred: Exporter otlp encountered the following error(s): the grpc server returns error Unknown error
```

**Desktop (please complete the following information):**
```
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165
```

### PR DESCRIPTION
**Pull request by Geal**
Fix #149 

the endpoint address is often specified as host:port instead of a full
URL: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/README.md#getting-started

Unfortunately, the url crate would parse 'collector:4317' as an URL with
the 'collector' scheme and no host. It also will not recognize
'IP:port'.

This adds a layer to URl parsing to recognize those cases, and configure
the HTTPS scheme manually

### CODE REVIEW

File: crates/apollo-router/src/configuration/otlp/mod.rs [hunk 1]
```diff
@@ -80,6 +80,37 @@ impl ExportConfig {
...
+
+fn endpoint_url<'de, D>(deserializer: D) -> Result<Url, D::Error>
+where
+    D: Deserializer<'de>,
+{
+    let mut buf = String::deserialize(deserializer)?;
+
+    // support the case of a IP:port endpoint
+    if buf.parse::<std::net::SocketAddr>().is_ok() {
+        buf = format!("https://{}", buf);
```
Comment (o0Ignition0o) [inline crates/apollo-router/src/configuration/otlp/mod.rs:98]: should we document somewhere that we're falling back to https ?

**Review by o0Ignition0o — APPROVED** [review]
Lgtm, just a question about documentation

File: crates/apollo-router/src/configuration/otlp/mod.rs (hunk 1 above)
Comment (Geal) [reply crates/apollo-router/src/configuration/otlp/mod.rs:98]: in https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/README.md#getting-started "By default, TLS is enabled" so it's expected. But I agree that it should be in the documentation.
I'm planning to rewrite the part of the documentation about telemetry once this week's pull requests have settled a bit

File: crates/apollo-router/src/configuration/otlp/mod.rs [hunk 2]
```diff
@@ -80,6 +80,37 @@ impl ExportConfig {
...
+
+    let mut url = Url::parse(&buf).map_err(serde::de::Error::custom)?;
+
+    // support the case of 'collector:4317' where url parses 'collector'
+    // as the scheme instead of the host
+    if url.host().is_none() && (url.scheme() != "http" || url.scheme() != "https") {
+        buf = format!("https://{}", buf);
+
+        url = Url::parse(&buf).map_err(serde::de::Error::custom)?;
+    }
```
Comment (cecton) [inline crates/apollo-router/src/configuration/otlp/mod.rs:109]: Why not use set_scheme?

File: crates/apollo-router/src/configuration/otlp/mod.rs [hunk 3]
```diff
@@ -80,6 +80,37 @@ impl ExportConfig {
     }
 }
 
+#[derive(Debug, Clone, Deserialize, Serialize)]
+#[serde(transparent)]
+pub struct EndpointUrl {
+    #[serde(deserialize_with = "endpoint_url")]
```
Comment (cecton) [inline crates/apollo-router/src/configuration/otlp/mod.rs:86]: You can probably do this trick in the ExportConfig struct directly and skip EndpointUrl struct entirely

File: crates/apollo-router/src/configuration/otlp/mod.rs (hunk 2 above)
Comment (Geal) [reply crates/apollo-router/src/configuration/otlp/mod.rs:109]: because we would end up with the url "https://4317" instead of "https://collector:4317". The url crate recognizes "collector" as the scheme in "collector:4317"

File: crates/apollo-router/src/configuration/otlp/mod.rs (hunk 3 above)
Comment (Geal) [reply crates/apollo-router/src/configuration/otlp/mod.rs:86]: I tried various approaches with or without EndpointUrl, like `serde(flatten)` and those did not work. Unfortunately I do not remember the error messages

Comment (cecton) [reply crates/apollo-router/src/configuration/otlp/mod.rs:86]:
```rust
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields, rename_all = "snake_case")]
pub struct ExportConfig {
    #[serde(deserialize_with = "endpoint_url")]
    pub endpoint: Option<Url>,
    pub protocol: Option<Protocol>,
    pub timeout: Option<u64>,
}

fn endpoint_url<'de, D>(deserializer: D) -> Result<Option<Url>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let buf = String::deserialize(deserializer)?;
    Ok(Some(Url::parse(&buf).map_err(serde::de::Error::custom)?))
}
```

Comment (cecton) [reply crates/apollo-router/src/configuration/otlp/mod.rs:86]: With the http fix:
```rust
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields, rename_all = "snake_case")]
pub struct ExportConfig {
    #[serde(deserialize_with = "endpoint_url")]
    pub endpoint: Option<Url>,
    pub protocol: Option<Protocol>,
    pub timeout: Option<u64>,
}

fn endpoint_url<'de, D>(deserializer: D) -> Result<Option<Url>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let mut buf = String::deserialize(deserializer)?;
    if !buf.starts_with("http") {
        buf.insert_str(0, "https://");
    }
    Ok(Some(Url::parse(&buf).map_err(serde::de::Error::custom)?))
}
```

Comment (Geal) [reply crates/apollo-router/src/configuration/otlp/mod.rs:86]: did you test it? That was the first thing I tried. IIRC It complains that it expects to find an endpoint field.
From what I understand, with that annotation, serde-json first looks for an endpoint field, then passes its content to the function that then returns an Option. Instead of recognizing the field as optional

Comment (cecton) [reply crates/apollo-router/src/configuration/otlp/mod.rs:86]: ah yes you need to add `default` so it can fallback to None before it fails to parse:
```rust
    #[serde(deserialize_with = "endpoint_url", default)]
```

Comment (Geal) [reply crates/apollo-router/src/configuration/otlp/mod.rs:86]: nice! updating the code rn

**Review by cecton — APPROVED** [review]
