### PR TITLE
coprocessor: add support for deferred responses and fix body data type

### LINKED ISSUE #3015: router coprocessor externalisation can't convert deferred responses into JSON
When the router tries to deserialize a multi-part deferred response into a JSON value for externalization, that, for obvious reasons, doesn’t work.

There are a number of options for fixing this, but it is likely that the best fix is to simply transmit the bytes to the coprocessor for processing rather than trying to convert the body into JSON.

### PR DESCRIPTION
**Pull request by garypen**
Modifies the implementation to process deferred results gradually rather than blocking.
Changes the coprocessor router body payload to be a String, rather than a JSON Value (Map, effectively)

In retrospect, it was a mistake to have made the Router coprocessor body payload be a JSON Value. It should just be a String (Bytes). There are reasons for this:
 - Users want to interact with raw bytes at the Router level.
 - Defer responses are structured, but aren’t JSON values and are a stream.
 - Supergraph stage is where the body is guaranteed to be valid JSON.

Since we should modify the payload of the router coprocessor calls to be bytes rather than JSON, we must do that as either:
A coprocessor protocol revision
A coprocessor protocol breaking change

If we had chosen 1, then we would need to decide how to implement support in the router for multiple protocol versions (which doesn’t exist as yet). Probably the best solution is to provide a configuration option as part of coprocessor configuration and default to either the oldest or newest (to be argued about) version.

This change, simply updates the implementation without revving the protocol. Users will need to modify their coprocessors after router version 1.x (when we release the fix).

Fixes #3015

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [ ] Changes are compatible[^1]
- [x] Documentation[^2] completed
- [x] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [x] Unit Tests
    - [x] Integration Tests
    - [x] Manual Tests

**Exceptions**

Changes are **not** compatible, but we have made the decision to fix this incompatibly now before the feature is widely used.
I created a simple co-processor which I could use to validate that my changes were working as expected.

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

### CODE REVIEW

File: apollo-router/src/plugins/coprocessor.rs [hunk 1]
```diff
@@ -533,18 +533,24 @@ where
...
-                            ))
-                            .extension_code("EXERNAL_DESERIALIZATION_ERROR")
-                            .build()])
-                        .build()
-                });
+        // At this point our body is a String. Try to get a valid JSON value from it
+        let body_as_value = co_processor_output
+            .body
+            .and_then(|b| serde_json::from_str(&b).ok())
+            .unwrap_or(serde_json::Value::Null);
```
Comment (o0Ignition0o) [inline apollo-router/src/plugins/coprocessor.rs:540]: Does the coprocessor /need to/ return a JSON body when it `ControlFlow::Break`s at the RouterService Request level? Why?

File: apollo-router/src/services/external.rs [hunk 2]
```diff
@@ -96,10 +95,85 @@ pub(crate) struct Externalizable<T> {
...
+        body: Option<T>,
+        context: Option<Context>,
+        status_code: Option<u16>,
+        method: Option<String>,
+        path: Option<String>,
+        sdl: Option<String>,
+    ) -> Self {
+        assert!(matches!(
+            stage,
+            PipelineStep::RouterRequest | PipelineStep::RouterResponse
```
Comment (o0Ignition0o) [inline apollo-router/src/services/external.rs:121]: I wish this would fail at build time, but it would require two layers of enums... :/

**Review by o0Ignition0o — APPROVED** [review]
Kudos on the docs update and the turnaround pace!

One question around RouterService Request controlflow::break, the rest lgtm!

**Review by bnjjj — APPROVED** [review]

**Review by BrynCooke — APPROVED** [review]

File: apollo-router/src/plugins/coprocessor.rs [hunk 3]
```diff
@@ -610,46 +616,57 @@ where
...
-        status_code: status_to_send,
-        sdl,
-        uri: None,
-        path: None,
-        method: None,
-        service_name: None,
-    };
+    let sdl_to_send = response_config.sdl.then(|| sdl.clone().to_string());
+
+    let payload = Externalizable::router_builder()
```
[the remark this answers is not in the document]
Comment (garypen) [reply apollo-router/src/plugins/coprocessor.rs:656]: Thank you! You prompted me with your comment. :)

File: apollo-router/src/plugins/coprocessor.rs (hunk 1 above)
Comment (o0Ignition0o) [reply apollo-router/src/plugins/coprocessor.rs:540]: WFM!

File: .changesets/fix_garypen_3015_and_friends.md [hunk 4]
```diff
@@ -0,0 +1,11 @@
...
+
+The current implementation of the RouterResponse processing for coprocessors forces buffering of response data before passing the data to a coprocessor. This is a bug, because deferred responses should be processed progressively with a stream of calls to the coprocessor as each chunk of data becomes available.
+
+Furthermore, the data type is assumed to be valid JSON for both RouterRequest and RouterResponse coprocessor processing. This is a bug, because data at this stage of processing is not necessarily valid JSON. This is a particular issue when dealing with deferred RouterResponses.
+
+This change fixes both of these bugs by modifying the router so that coprocessors are invoked with a body payload which is a JSON String, not a JSON Object. Furthermore, the router now processes each chunk of response data separately so that a coprocessor will receive multiple calls (once for each chunk) for a deferred response.
+
+For more details about how this works: [coprocessor documentation](https://www.apollographql.com/docs/router/customizations/coprocessor/)
+
+By [@garypen](https://github.com/garypen) in https://github.com/apollographql/router/pull/3104
```
Comment (abernix) [inline .changesets/fix_garypen_3015_and_friends.md:11]:
```suggestion
### Fix router deferred response and body type issues ([Issue #3015](https://github.com/apollographql/router/issues/3015))

The current implementation of the `RouterResponse` processing for coprocessors forces buffering of response data before passing the data to a coprocessor. This is a bug, because deferred responses should be processed progressively with a stream of calls to the coprocessor as each chunk of data becomes available.

Furthermore, the data type was assumed to be valid JSON for both `RouterRequest` and `RouterResponse` coprocessor processing. This is also a bug, because data at this stage of processing was never necessarily valid JSON. This is a particular issue when dealing with deferred (when using `@defer`) `RouterResponses`.

This change fixes both of these bugs by modifying the router so that coprocessors are invoked with a `body` payload which is a JSON `String`, not a JSON `Object`. Furthermore, the router now processes each chunk of response data separately so that a coprocessor will receive multiple calls (once for each chunk) for a deferred response.

For more details about how this works see the [coprocessor documentation](https://www.apollographql.com/docs/router/customizations/coprocessor/).

By [@garypen](https://github.com/garypen) in https://github.com/apollographql/router/pull/3104
```
