### PR TITLE
fix histogram metrics in OTLP

### LINKED ISSUE #2493: apollo_router_processing_time is ever increasing
**Describe the bug**
The newly introduced `apollo_router_processing_time` is ever increasing. This doesn't make much sense, or does it? The free fall in the graph is a router restart.

Screenshot 2023-01-27 at 20 32 21

### PR DESCRIPTION
**Pull request by Geal**
Fix #2493

with the inexpensive selector, histogram are only reported as gauges, and so they will be incorrectly interpreted when reaching Datadog

### CODE REVIEW

**Comment by Geal** [comment]
I'm not fixed on the list of buckets we actually push, we can change it (I think the higher buckets, at more than 1mn are less useful)

File: apollo-router/src/plugins/telemetry/metrics/otlp.rs [hunk 1]
```diff
@@ -41,8 +42,33 @@ impl MetricsConfigurator for super::super::otlp::Config {
             Some(exporter) => {
                 let exporter = opentelemetry_otlp::new_pipeline()
                     .metrics(
-                        opentelemetry::sdk::metrics::selectors::simple::inexpensive(),
-                        aggregation::stateless_temporality_selector(),
+                        selectors::simple::histogram([
+                            // 1-500 ms
```
Comment (BrynCooke) [inline apollo-router/src/plugins/telemetry/metrics/otlp.rs:46]: Just want to sanity check the units here. The fact that units are floats make me think they are in SI rather than millis.

File: apollo-router/src/plugins/telemetry/metrics/otlp.rs [hunk 2]
```diff
@@ -41,8 +42,33 @@ impl MetricsConfigurator for super::super::otlp::Config {
             Some(exporter) => {
                 let exporter = opentelemetry_otlp::new_pipeline()
                     .metrics(
```
Comment (Meemaw) [inline apollo-router/src/plugins/telemetry/metrics/otlp.rs:44]: Might make sense to add a comment for this, as to why `inexpensive()` selector is not used.

File: apollo-router/src/plugins/telemetry/metrics/otlp.rs (hunk 1 above)
Comment (Geal) [reply apollo-router/src/plugins/telemetry/metrics/otlp.rs]: all the values the router generates are in seconds. I just changed and aligned those histograms to the ones used in prometheus

Comment (Geal) [reply apollo-router/src/plugins/telemetry/metrics/otlp.rs]: there are conventions like https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/http-metrics/#metric-httpclientduration

so far in the router we went with using the second as base unit, not the millisecond, so 1-500ms translates as 0.001..0.5

**Review by BrynCooke — APPROVED** [review]

File: apollo-router/src/plugins/telemetry/metrics/otlp.rs (hunk 1 above)
Comment (BrynCooke) [reply apollo-router/src/plugins/telemetry/metrics/otlp.rs]: That's good to know.
