### PR TITLE
Fix: Update the scaffold template so it works with streams.

### LINKED ISSUE #1247: Update the scaffold template so it works with Streams
The scaffolded plugins still use the former definitions:

``` rust

 fn router_service(
        &mut self,
        service: BoxService<RouterRequest, RouterResponse, BoxError>,
    ) -> BoxService<RouterRequest, RouterResponse, BoxError> { }
```

While they now need to use

```rust

    fn router_service(
        &mut self,
        service: BoxService<
            RouterRequest,
            RouterResponse<BoxStream<'static, ResponseBody>>,
            BoxError,
        >,
    ) -> BoxService<RouterRequest, RouterResponse<BoxStream<'static, ResponseBody>>, BoxError> { }
```

Steps to follow:

Add a dependency to futures in the template toml:

```futures = "0.3.21"```

Add use statements:

```rust
use futures::stream::BoxStream;
use apollo_router::ResponseBody;

```

update the tests:

```rust

    #[tokio::test]
    async fn basic_test() -> Result<(), BoxError> {
        // Define a configuration to use with our plugin
        let conf = Conf {
            message: "Starting my plugin".to_string(),
        };

        // Build an instance of our plugin to use in the test harness
        let plugin = ResponseTimings::new(conf).await.expect("created plugin");

        // Create the test harness. You can add mocks for individual services, or use prebuilt canned services.
        let mut test_harness = PluginTestHarness::builder()
            .plugin(plugin)
            .schema(Canned)
            .build()
            .await?;

        // Send a request
        let mut result = test_harness.call_canned().await?;

        let first_response = result
            .next_response()
            .await
            .expect("couldn't get primary response");

        if let ResponseBody::GraphQL(graphql) = first_response {
            assert!(graphql.data.is_some());
        } else {
            panic!("expected graphql response")
        }

        // You could keep calling result.next_response() until it yields None if you're expexting more parts.
        assert!(result.next_response().await.is_none());
        Ok(())
    }
```

### PR DESCRIPTION
**Pull request by o0Ignition0o**
fixes #1247

Release v0.9.4 changed the way we deal with Response objects, which can now be streams.
This Pull request updates the scaffold template so it generates plugins that are compatible with the new Plugin API.

### CODE REVIEW

**Comment by o0Ignition0o** [comment]
Not quite sure how to test this effectively...

**Review by Geal — APPROVED** [review]

File: apollo-router-scaffold/src/lib.rs [hunk 1]
```diff
@@ -74,7 +74,7 @@ mod test {
         )?;
         test_build(&temp_dir)?;
 
-        drop(temp_dir);
+        // drop(temp_dir);
```
Comment (bnjjj) [inline apollo-router-scaffold/src/lib.rs]: Did you know about that crate https://github.com/bnjjj/tmp_env :p Just sayin
