### PR TITLE
fix fragment spread response formatting with aliased typename #4348

### LINKED ISSUE #4348: Router not GraphQL spec compliant with Abstract spreads in object scopes
The functionality described in [section 5.5.2.3.2 of the GraphQL Spec](https://spec.graphql.org/October2021/#sec-Abstract-Spreads-in-Object-Scope), Abstract spreads within an object scope do not appear to work in Apollo Router. All examples shown below are with the published Apollo Router executable **v1.35.0**

## Unions with no nested types
Using a schema as follows, a union is made on two objects, Cat and Dog. Both objects are similar to one another, and a field under query is created to return a Dog object

```graphql
type Query {
  dog: Dog
}

type Dog {
  name: String!
  nickname: String!
  barkVolume: Int
}

type Cat {
  name: String!
  nickname: String!
  meowVolume: Int
}

union CatOrDog = Cat | Dog
```

The following is the response from a query to a [gqlgen](https://gqlgen.com/getting-started/) server, that specifies the root level dog field and spreads the union CatOrDog under it.

image

The Apollo Router returns a similar response for the same schema, but adds on the field unique to the Cat type, meowVolume to the response payload even though it does not exist on type Dog

image

**Expected behavior**
The router should not be sending back `meowVolume` in this case.

## Union with one nested type
The schema is modified to instead nest Dog under an arbitrary wrapper object called NestedDog. The union is now on Cat and NestedDog

```graphql
type Query {
  nestedDog: NestedDog
}

type NestedDog {
  dog: Dog!
}

type Dog {
  name: String!
  nickname: String!
  barkVolume: Int
}

type Cat {
  name: String!
  nickname: String!
  meowVolume: Int
}

union CatOrDog = Cat | NestedDog
```

The query was modified accordingly, and making the query below to a gqlgen server results in the following response:

image

However, the Apollo Router seems to completely null out the Dog type for the same query:

image

Removing the spread on the Cat object fixes this issue and allows the response to pass through successfully

image

## Additional Context
The request sent to the subgraph (gqlgen server) and response received from the subgraph were logged using a rhai script (this holds for both queries tested under the union with nested type):

**Subgraph Request:**
```graphql
query test__example__0 {
  nestedDog {
    __isCatOrDog: __typename
    dog {
      name
      nickname
      barkVolume
    }
  }
}

```
**Subgraph Response:**
```json
{
 "data": {
   "nestedDog": {
     "__isCatOrDog": "NestedDog",
     "dog": {
       "barkVolume": 7,
       "name": "Fido",
       "nickname": "Fi"
     }
   }
 }
}

```

### PR DESCRIPTION
**Pull request by bnjjj**
When you had an aliased `__typename` (example `myAlias: __typename`) in a fragment spread, the response formatting was wrong.

Fixes #4348

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [x] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [x] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [x] Unit Tests
    - [ ] Integration Tests
    - [x] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

### CODE REVIEW

**Comment by abernix** [comment]
Just noting that https://github.com/apollographql/router/pull/4402 targets this right now. (creating context)

File: apollo-router/src/query_planner/tests.rs [hunk 1]
```diff
@@ -1458,9 +1455,7 @@ async fn typename_propagation2() {
                         "representations": [{
                             "__typename": "Book",
                             "bookId": "book1",
-                            "author": {
-                                "fullName": "Ada"
-                            }
+                            "author": null
```
Comment (Geal) [inline apollo-router/src/query_planner/tests.rs:1458]: why this change?

File: .changesets/fix_bnjjj_fix_4348.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+### Fix fragment spread response formatting with aliased typename ([Issue #4348](https://github.com/apollographql/router/issues/4348))
+
+When you had an aliased `__typename` (example `myAlias: __typename`) in a fragment spread, the response formatting was wrong.
```
Comment (Geal) [inline .changesets/fix_bnjjj_fix_4348.md:3]: the changeset should probably reflect the actual issue, which is that response formatting was confused by fragments on unions

File: apollo-router/src/spec/fragments.rs [hunk 3]
```diff
@@ -25,17 +26,24 @@ impl Fragments {
...
                     selection_set: fragment
                         .selection_set
                         .selections
                         .iter()
                         .filter_map(|selection| {
+                            if let Some(field) = selection.as_field() {
+                                if field.name.as_str() == TYPENAME && field.alias.is_some() {
+                                    aliased_typename = field.alias.as_ref().map(|f| f.to_string());
+                                }
+                            }
```
Comment (Geal) [inline apollo-router/src/spec/fragments.rs:41]: the aliased typename field should be removed now, we don't need it anymore

**Review by Geal — CHANGES_REQUESTED** [review]

File: apollo-router/src/query_planner/tests.rs (hunk 1 above)
Comment (bnjjj) [reply apollo-router/src/query_planner/tests.rs:1458]: Because apparently that's the query planner is asking for. If I don't do this I have an error telling me that no mock request is matching

Comment (Geal) [reply apollo-router/src/query_planner/tests.rs:1458]: right, I saw that, it's ok

**Review by Geal — APPROVED** [review]
