### PR TITLE
fix: improve the configuration error report

### LINKED ISSUE #921: Bad configuration error report
if you try to put this config:

```yaml
server:
  # The socket address and port to listen on
  # Defaults to 127.0.0.1:4000
  listen: 127.0.0.1:4000
  bad:
    value: error
```

you will have this error:

```
2022-04-26T15:48:28.991268Z ERROR apollo_router: configuration had errors:
1. /server

#
server:
  # The socket address and port to listen on
  # Defaults to 127.0.0.1:4000
  listen: 127.0.0.1:4000
        ^----- Additional properties are not allowed ('bad' was unexpected)
```

it could be great to have: 

```
2022-04-26T15:48:28.991268Z ERROR apollo_router: configuration had errors:
1. /server

#
server:
  # The socket address and port to listen on
  # Defaults to 127.0.0.1:4000
  listen: 127.0.0.1:4000
  bad:
  ^----- Additional properties are not allowed ('bad' was unexpected)
```

### PR DESCRIPTION
**Pull request by bnjjj**
close #921 

What we had before for this kind of bad configuration:

```yaml
server:
  # The socket address and port to listen on
  # Defaults to 127.0.0.1:4000
  listen: 127.0.0.1:4000
  bad: "donotwork"
  another_one: true
```

+ Previous report:

```
configuration had errors: 
1. /server


server:
   # The socket address and port to listen on
   # Defaults to 127.0.0.1:4000
   listen: 127.0.0.1:4000
          ^-----> Additional properties are not allowed ('bad', 'another_one' were unexpected)
```

+ Here is the new report:

```
configuration had errors: 
1. /server


server:
┌   # The socket address and port to listen on
|   # Defaults to 127.0.0.1:4000
|   listen: 127.0.0.1:4000
|   bad: "donotwork"
|   another_one: true
└-----> Additional properties are not allowed ('bad', 'another_one' were unexpected)
```

We had a bug previously that only highlighted the first field of the map with unknown properties.

### CODE REVIEW

File: apollo-router/src/configuration/mod.rs [hunk 1]
```diff
@@ -460,35 +461,88 @@ pub fn validate_configuration(raw_yaml: &str) -> Result<(), ConfigurationError>
...
+                                        e.instance_path,
+                                        lines,
+                                        " ".repeat(0.max(marker.col())),
+                                        e
+                                    ))
+                                }
+                                seq_element @ yaml::Value::Sequence(_, m) => {
+                                    let (start_marker, end_marker) = (m, seq_element.end_marker());
+
+                                    let offset = 0.max(start_marker.line() as isize - 5) as usize;
```
Comment (garypen) [inline apollo-router/src/configuration/mod.rs:496]: NIT: Make 5 a constant with a good name in all places where it is used.

also, wouldn't this be cleaner as
```
let offset = 5.max(start_marker.line()) - 5;
```
? (still using the well named CONSTANT)

**Review by garypen — APPROVED** [review]
