### PR TITLE
fix(entity_caching): do not include other fields from representation variable than the entity keys

### LINKED ISSUE #6673: Entity caching uses stringified representations within entity cache key
## Describe the bug

Enttiy caching works by calculating a cache key that can be repeated for easier invalidation. Unfortunately the code: https://github.com/apollographql/router/blob/7a015fdadf416495f961fe621569580b8cf1181a/apollo-router/src/plugins/cache/entity.rs#L1337

Uses the entity _representation_, meaning that if a type uses `@requires`, it'd be included as part of the cache key. 

Furthermore, this representation is hashed as provided by either the router or user, meaning that the hash key is dependent on the order of a representation's values. For example:

```json
{
    "id": "1234",
    "id2": "5678"
}
```

is not the same as:

```json
{
  "id2": "5678",
  "id": "1234"
}
```

For purposes of hash calculation. 

This poses two problems: 

- Invalidation is unable to be easily used, as `@requires` are dynamically required as part of the request (and can be quite large payloads), meaning that users have to include all required inputs beyond keys, as well as matching the original order in which the router sent them
- The cache key includes data that isn't related to the actual key of the entity, so invalidating a single entity type isn't possible easily

## To Reproduce

For literal representation in the invalidation API: 

1. Configure the router and entity caching (with invalidation)with a Redis server
2. Use a `monitor` command to monitor the Redis commands issued by the router
3. Run a invalidation request, ordering the keys in different ways. You'll note the hash value in the SCAN command is different based on ordering

For literal representations within the cache:

1. Configure the router and entity caching (with invalidation)with a Redis server
2. Use a `monitor` command to monitor the Redis commands issued by the router
3. Have a schema that includes a type that has a `@requires` statement, and issue a request for that entity that includes the field that has `@requires` applied
5. issue a request for that entity that includes the field that has `@requires` applied
6. Issue a second request _without_ the field that has the `@requires` applied
7. Note that the hash prefixes differ

## Expected behavior

Keys are calculated without any required field data as well as ignoring ordering in invalidation requests.

### PR DESCRIPTION
**Pull request by bnjjj**
Separate entity keys and representation variable value in the cache key to avoid issues with `@requires` for example.

close #6673 

 

[ROUTER-1007]: https://apollographql.atlassian.net/browse/ROUTER-1007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apollo-router/src/plugins/cache/entity.rs [hunk 1]
```diff
@@ -1344,22 +1410,55 @@ fn extract_cache_keys(
...
+                representation.insert(key, val);
+            });
         res.push(key);
     }
     Ok(res)
 }
 
-pub(crate) fn hash_entity_key(representation: &Value) -> String {
+/// Use it specifically for keys field set because we don't check for fragment spread
+fn get_root_field_names(selection_set: &SelectionSet) -> Vec<Name> {
```
Comment (SimonSapin) [inline apollo-router/src/plugins/cache/entity.rs:1432]: With apollo-compiler 1.27.0 released today `selection_set.root_fields()` returns an iterator that can replace this function

File: apollo-router/src/plugins/cache/tests.rs [hunk 2]
```diff
@@ -152,6 +152,9 @@ impl Mocks for MockStore {
 
 #[tokio::test]
 async fn insert() {
+    let mut parser = apollo_compiler::parser::Parser::new();
+    let schema = parser.parse_schema(SCHEMA, "test.graphql").unwrap();
+    let valid_schema = Arc::new(schema.validate().unwrap());
```
Comment (SimonSapin) [inline apollo-router/src/plugins/cache/tests.rs:157]: If you’re not changing `Parser` parameters you can use `Schema::parse_and_validate()`

Same a few more times below

**Review by SimonSapin — APPROVED** [review]
Looks good so far, but since it’s draft I assume you want to make more changes?

**Comment by bnjjj** [comment]
> Looks good so far, but since it’s draft I assume you want to make more changes?
@SimonSapin yes tests

File: apollo-router/src/plugins/cache/entity.rs [hunk 3]
```diff
@@ -500,10 +514,33 @@ impl EntityCache {
...
+    let mut subgraph_enums = HashMap::new();
+    if let Some(graph_enum) = supergraph_schema.get_enum("join__Graph") {
+        subgraph_enums.extend(graph_enum.values.iter().filter_map(
+            |(enum_name, enum_value_def)| {
+                let subgraph_name = enum_value_def
+                    .directives
+                    .get("join__graph")
+                    .and_then(|directive| directive.specified_argument_by_name("name"))
+                    .and_then(|arg| arg.as_str())?
+                    .to_string();
```
Comment (SimonSapin) [inline apollo-router/src/plugins/cache/entity.rs:534]: Nit (feel free to ignore): I think this might work:
```suggestion
                    .get("join__graph")?
                    .specified_argument_by_name("name")?
                    .as_str()?
                    .to_string();
```

**Review by SimonSapin — APPROVED** [review]

**Comment by abernix** [comment]
@bnjjj The test failure here looks potentially related, so I'm going to disable auto-merge while you take a look.

**Comment by bnjjj** [comment]
Good catch @abernix . I fixed it :) thank you :)
