### PR TITLE
fix: set `operation_name` tracing attribute to empty on unnamed, single-op requests

### LINKED ISSUE #481: Remove "-" as default operation_name if none is provided, and add it in the stats result key only
I mean, that's a choice that is made specifically in the context of "the 'stats result key'". I don't think anything else in Apollo does "- as empty operation name". I just wanted to not have an empty "comment" in that format. Probably doesn't make sense to do it anywhere other than stats result key formatting.

_Originally posted by @glasser in https://github.com/apollographql/router/pull/433#discussion_r807391341_

### PR DESCRIPTION
**Pull request by abernix**
When GraphQL operation names are not nececessary to execute an operation (i.e., when there is only a single operation in a GraphQL document) and the GraphQL operation is _not_ named (i.e., it is anonymous), the `operation_name` attribute on the trace spans that are associated with the request will no longer contain a single hyphen character (`-`) but will instead be an empty string.  This matches the way that these operations are represented during the GraphQL operation's life-cycle as well.

Fixes #481

### CODE REVIEW

File: apollo-router/src/warp_http_server_factory.rs [hunk 1]
```diff
@@ -345,7 +345,7 @@ where
     name = "graphql_request",
     fields(
         query = %request.query.clone().unwrap_or_default(),
-        operation_name = %request.operation_name.clone().unwrap_or_else(|| "-".to_string()),
+        operation_name = %request.operation_name.clone().unwrap_or_else(|| "".to_string()),
```
Comment (garypen) [inline apollo-router/src/warp_http_server_factory.rs:348]: That's going to break the studio usage though. If you look at [stats_report_key() in apollo_open](https://github.com/apollographql/router/blob/9537ef271ac76e449220c0ed5abe1a8632955673/apollo-router/src/apollo_telemetry.rs#L388) you'll note that we assume the default name for an operation there is "-" which is what we want for stats reporting.

To keep things working, you'll need to modify `stats_report_key()` to check if `op_name` is `""` and, if it is, then update that logic to substitute `"-"` as the `op_name`. The comment there will need to be updated as well.

**Review by garypen — CHANGES_REQUESTED** [review]
If my comment doesn't make sense, let me know.

File: apollo-router/src/apollo_telemetry.rs [hunk 2]
```diff
@@ -319,7 +320,9 @@ impl SpanExporter for Exporter {
                     .to_string();
                 let operation_name = span
                     .attributes
-                    .get(&opentelemetry::Key::from_static_str("operation_name"));
+                    .get(&opentelemetry::Key::from_static_str("operation_name"))
+                    .unwrap_or(&anonymous_or_optional_operation_name);
```
Comment (garypen) [inline apollo-router/src/apollo_telemetry.rs:324]: I like this. Super safe in case the instrumentation is ever edited or removed...

File: apollo-router/src/apollo_telemetry.rs [hunk 3]
```diff
@@ -446,9 +438,16 @@ fn stats_report_key(op: Option<&opentelemetry::Value>, query: &str) -> String {
         tracing::warn!("Could not find required definition: {}", query);
         return GRAPHQL_UNKNOWN_OPERATION_NAME.to_string();
     }
-    tracing::debug!("looking for operation: {}", op_name);
+    tracing::debug!("looking for operation: {}", if op_name.is_empty() { "{empty}" } else { &op_name });
```
Comment (garypen) [inline apollo-router/src/apollo_telemetry.rs:441]: I'm fine with using `{empty}` but just wonder if we should use `-` to be consistent with what we actually end up replacing the op_name with...

**Review by garypen — APPROVED** [review]
One tiny comment about {empty} vs - . This is a nice improvement on existing behaviour.

File: apollo-router/src/apollo_telemetry.rs (hunk 3 above)
Comment (abernix) [reply apollo-router/src/apollo_telemetry.rs]: 👍  Tweaked in 7dc8302937ce408668d540d08116ec98eeebf7cb.

File: CHANGELOG.md [hunk 4]
```diff
@@ -22,6 +22,16 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 
  -->
 
+# Upcoming
+
+> Not yet in a release!
+
+## :bug: Fixes
+
+- **Anonymous operation names are now empty in tracing** ([PR #TODO](https://github.com/apollograpqhl/router/pull/TODO))
```
Comment (abernix) [inline CHANGELOG.md:31]:
```suggestion
- **Anonymous operation names are now empty in tracing** ([PR #525](https://github.com/apollograpqhl/router/pull/525))
```
