### PR TITLE
Query variables validation

### LINKED ISSUE #62: Variable types are not validated
**Describe the bug**
When passing in variables their types should be validated against the schema and the entire request rejected if they are incorrect.

Requires schema parsing to complete.

### PR DESCRIPTION
**Pull request by cecton**
## Changes
 -  ~~Remove unneeded `Option` around `Request`'s variables`: this has been moved to #257 (review this first to reduce the diff size here :brain:)~~
 -  Add error variant `ValidationInvalidTypeVariable` for variables of invalid type
 -  ~~Introduce new module `spec` for our higher level representation of GraphQL's Schema and Query: this has been moved to #258 (review this first to reduce the diff size here :brain:)~~
 -  ~~Clean-up prelude and added a note: this has been moved to #258 (review this first to reduce the diff size here :brain:)~~
 -  Removed `schema` parameter from `Query`'s constructor: if the schema changes we don't want the query to be executed on a wrong
    schema. So unless we include the Schema to the hashing (Hash) we should make this a parameter of the methods of `Query`.
 -  Introduce public method `validate_variables` on `Query` that allows type validation of the request's variable (the whole point of the damn PR, see #62)
 -  Add a lot of transformation from apollo-rs's ast to our own (private) higher level representation API: FieldType, ObjectType, Interface, ...
 -  Refactor fragments creation to its own type so it can be re-used in the `Schema` and `Query`
 -  Refactor formatting tests so we don't need to update everything when our API changes
 -  Add a bunch of type validation tests
 -  Made `Schema`'s `is_subtype()` private: we don't need to expose that to the user (at least not for now...)
 -  Parse and validate the query before making a query plan
 -  Fix invalid integration tests for missing variables: we used to check for the variables to be present before running the query plan. The implementation was not correct as the variables are optional by default unless the type is a non-null type. I removed this entirely in favor of this new variable type validation.
 -  Fix a tracing stuff according to ADR on telemetry.
 -  Add documentation
 -  Disable parse error printing if log level is OFF

Fixes #62

### CODE REVIEW

**Comment by cecton** [comment]
Waiting on #233 before continuing

File: apollo-router-core/src/spec/field_type.rs [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+    NonNull(Box<FieldType>),
+    String,
+    Int,
+    Float,
+    Id,
+    Boolean,
+}
+
+impl FieldType {
+    pub(crate) fn validate_value(&self, value: &Value, schema: &Schema) -> bool {
```
Comment (o0Ignition0o) [inline apollo-router-core/src/spec/field_type.rs:18]: is_valid? I d expect validate_value to return Result<()>

File: apollo-router-core/src/spec/query.rs [hunk 2]
```diff
@@ -23,15 +26,25 @@ impl Query {
     ///
     /// This will discard unrequested fields and re-order the output to match the order of the
     /// query.
-    #[tracing::instrument(level = "trace")]
-    pub fn format_response(&self, response: &mut Response, operation_name: Option<&str>) {
+    #[tracing::instrument(skip_all, level = "trace")]
+    pub fn format_response(
```
Comment (o0Ignition0o) [inline apollo-router-core/src/spec/query.rs:30]: Maybe followup: Is there a chance this can be done progressively in the execute steps?

File: apollo-router-core/src/spec/query.rs [hunk 3]
```diff
@@ -45,29 +58,24 @@ impl Query {
...
-            .fragments()
-            .map(|(key, value)| (key.clone(), value.clone()))
-            .collect::<HashMap<String, Vec<_>>>();
 
         let parser = apollo_parser::Parser::new(string.as_str());
         let tree = parser.parse();
+        let errors = tree
+            .errors()
+            .map(|err| format!("{:?}", err))
+            .collect::<Vec<_>>();
```
Comment (o0Ignition0o) [inline apollo-router-core/src/spec/query.rs:70]: nit: maybe do the let errors = tree.errors() step here, and the map / collect in the if ?

**Review by o0Ignition0o — COMMENTED** [review]
A couple of comments / questions, I haven't reviewed everything yet.

I'll need to checkout the code to understand the schema.rs / macros and everything.

File: apollo-router-core/src/error.rs [hunk 4]
```diff
@@ -240,15 +241,11 @@ struct ParserError {
...
-            errors: errors.cloned().collect(),
-        }
-    }
-
+    #[allow(clippy::needless_return)]
     pub fn print(&self) {
-        if atty::is(atty::Stream::Stdout) {
+        if LevelFilter::current() == LevelFilter::OFF {
+            return;
+        } else if atty::is(atty::Stream::Stdout) {
```
[the remark this answers is not in the document]
Comment (cecton) [reply apollo-router-core/src/error.rs:248]: I have really no preference at all on that. I can adapt as you prefer

File: apollo-router-core/src/spec/field_type.rs (hunk 1 above)
Comment (cecton) [reply apollo-router-core/src/spec/field_type.rs:18]: Very good point :sweat: naming's hard

File: apollo-router-core/src/spec/query.rs (hunk 3 above)
Comment (cecton) [reply apollo-router-core/src/spec/query.rs:70]: it's actually more optimal this way as the iterator is created only once and the vector does not allocate if the iterator has no elements.

Comment (cecton) [reply apollo-router-core/src/spec/query.rs:70]: it's not necessarily less readable either and it's not critical so if you prefer the way you did i'm fine with it

**Comment by Geal** [comment]
could you explain the logic behind removing the schema from the query? It should not change during the query, and even for the cache resolver, we create a new one from scratch on schema updates. And it feels like the schema has to be available during query parsing (right now we rely on the query planner to tell us a request is valid).
Is it done considering the use of the router as a library where the schema could be updated in another way?

File: apollo-router-core/src/spec/field_type.rs [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+        match (self, value) {
+            (FieldType::String, Value::String(_)) => true,
+            (FieldType::Int, Value::Number(number)) if !number.is_f64() => true,
```
Comment (Geal) [inline apollo-router-core/src/spec/field_type.rs:21]: why not `is_i64() || is_u64()` here? The documentation for `is_f64()` states that it would be equivalent but puts no guarantee on it: https://docs.serde.rs/serde_json/struct.Number.html#method.is_f64
(there are cases where I could see this failing, like a floating point number that requires 128 bits, because 64 bits is not required by the JSON spec)

File: apollo-router-core/src/spec/query.rs [hunk 6]
```diff
@@ -176,79 +194,68 @@ impl Query {
...
-                    self.apply_selection_set(selection_set, input, output);
+                    self.apply_selection_set(selection_set, input, output, schema);
                 }
                 Selection::FragmentSpread { name } => {
-                    if let Some(selection_set) = self.fragments.get(name) {
-                        self.apply_selection_set(selection_set, input, output);
+                    if let Some(selection_set) = self
+                        .fragments
+                        .get(name)
+                        .or_else(|| schema.fragments.get(name))
```
Comment (Geal) [inline apollo-router-core/src/spec/query.rs:203]: nice, that's less overhead than accumulating all of the schema's fragments at https://github.com/apollographql/router/pull/227/files#diff-3bc44ed791f17958d00dcbcdff996a241de8da3f2f5b1a3226ebf161245c4da3L50

File: apollo-router/src/lib.rs [hunk 7]
```diff
@@ -74,7 +74,7 @@ pub enum FederatedServerError {
 pub enum SchemaKind {
     /// A static schema.
     #[display(fmt = "Instance")]
-    Instance(graphql::Schema),
+    Instance(Box<graphql::Schema>),
```
Comment (Geal) [inline apollo-router/src/lib.rs:77]: why is the Box required now?

Comment (cecton) [reply apollo-router/src/lib.rs:77]: clippy big variant :disappointed:

**Comment by cecton** [comment]
> could you explain the logic behind removing the schema from the query? 

The query is hashed for the cache. Therefore if you have 2 identical queries but with 2 different schemas, you will get the same hash used in cache.

One alternative would be the hash the schema + the query but I think this will also take more space in memory.

> even for the cache resolver, we create a new one from scratch on schema updates

That's an external condition that make the things work but it clearly feels like the bug is coming for us. You know, that day when someone decide to change the cache thingy and make it faster and oops something unexpectedly broke :scream: 

Another way to see it is from API level. This object is hashable, fine, then the schema must hash with it if we store it otherwise it's just wrong. But I think it's best to pass the schema when doing the operation as it is less overhead (and less Arc references left around).

File: apollo-router-core/src/spec/field_type.rs (hunk 5 above)
Comment (cecton) [reply apollo-router-core/src/spec/field_type.rs:21]: I didn't think much about this. I'll fix it

**Comment by o0Ignition0o** [comment]
Oh that’s interesting, if the cache returns a query plan, then uniqueness / equality depends on the schema. This seems to call for two caches, one for the parser and one for the query plans

**Comment by cecton** [comment]
> This seems to call for two caches, one for the parser and one for the query plans

We already have that :grin:

**Comment by o0Ignition0o** [comment]
I’ll see myself out 😂🤣

**Comment by Geal** [comment]
ok so the thing here is I worried more about is said in
> Removed schema parameter from Query's constructor: if the schema changes we don't want the query to be executed on a wrong schema. So unless we include the Schema to the hashing (Hash) we should make this a parameter of the methods of Query.

than about what the code is actually doing, which does not change much. A big assumption in the way we execute query is that the schema will not change during the query: if we establish a query plan from a query and schema, when formatting at the end it should still be the same schema. This is the benefit that was given by carrying the schema along with the query, it guarantees that the same schema will be used for the entire life of the query, even if the calling code in apollo-router changes.

Now looking more at the code, this is mainly affecting the query cache, that caches the query parsed with apollo-rs and does not require the schema, than the CachingQueryPlanner who needs both query and schema. So it's ok. Maybe I just worry too much :sweat_smile:

File: apollo-router/src/lib.rs (hunk 7 above)
Comment (Geal) [reply apollo-router/src/lib.rs:77]: :see_no_evil:

File: apollo-router-core/src/spec/query.rs [hunk 8]
```diff
@@ -176,79 +194,68 @@ impl Query {
...
-                let selection_set = inline_fragment
-                    .selection_set()
-                    .expect("the node SelectionSet is not optional in the spec; qed")
-                    .selections()
-                    .into_iter()
-                    .map(Into::into)
-                    .collect();
-
-                Self::InlineFragment { selection_set }
+        if LevelFilter::current() >= LevelFilter::DEBUG {
```
Comment (Geal) [inline apollo-router-core/src/spec/query.rs:228]: could this entire block be gated by the `failfast` feature?

**Review by Geal — APPROVED** [review]

**Comment by Geal** [comment]
Perf test please

File: apollo-router-core/src/spec/query.rs (hunk 8 above)
Comment (cecton) [reply apollo-router-core/src/spec/query.rs:228]: Right now it's a mix of the 2:
- without failfast it prints a DEBUG warning only if the debug level is active
- with failfast and if the debug level is active, it panicks

So the performance hit is only if using level >= DEBUG

I think it's best this way but I don't mind changing it to failfast only.

**Comment by cecton** [comment]
> Perf test please

We now have automatic perf tests! ^_^ https://github.com/apollographql/router/pull/227/checks?check_run_id=4517674898

**Comment by abernix** [comment]
> We now have automatic perf tests! ^_^ https://github.com/apollographql/router/pull/227/checks?check_run_id=4517674898

@cecton From what I understand, they only get triggered and show up there if you explicitly request them using the phrasing above (or some variations, like _Je voudrais un test de perf_ 😉 ).  So they are semi-automated.

**Comment by cecton** [comment]
> This is the key point imo

To me the key point is more like: there is a way to use the API where you can instantiate the query with a one schema and do validation/formatting with another :sweat_smile: I don't need to look at the cache to know that it is wrong. Pretty sure it was done by me and completely unintentionally.

**Comment by cecton** [comment]
> @cecton From what I understand, they only get triggered and show up there if you explicitly request them using the phrasing above (or some variations, like _Je voudrais un test de perf_ wink ). So they are semi-automated.

Oh nice! There was one available before though:
- https://apollographql.grafana.net/d/dffCG6n7k/perf?orgId=1&from=1639473471000&to=1639473749000&var-test_id=pr-5cdeaec9-2prvj
- https://apollographql.grafana.net/d/dffCG6n7k/perf?orgId=1&from=1639414084000&to=1639414319000&var-test_id=pr-13045c51-ll6xb

File: apollo-router-core/src/spec/query.rs (hunk 8 above)
Comment (Geal) [reply apollo-router-core/src/spec/query.rs:228]: I do not think a panic is a behaviour we want, even in debug. If someone wants to see more logs in a production system and activates debug logs, the expectation is that it should not trigger more panics

**Comment by cecton** [comment]
Oh my branch makes huge perf improvement :joy: that's probably not right lol

**Comment by cecton** [comment]
Perf test please

**Comment by Geal** [comment]
> Oh my branch makes huge perf improvement 😂 that's probably not right lol

It looks like it compares to one of my failed attempts in the mutex PR 🤭

File: apollo-router-core/src/spec/query.rs (hunk 2 above)
Comment (o0Ignition0o) [reply apollo-router-core/src/spec/query.rs:30]: Oh by progressively I meant chunks by chunks as they arrive, but I might be missing context here

File: apollo-router-core/src/spec/query.rs (hunk 3 above)
Comment (o0Ignition0o) [reply apollo-router-core/src/spec/query.rs:70]: That's right, It only happens in the unhappy path, nevermind!

File: apollo-router-core/src/spec/field_type.rs (hunk 1 above)
Comment (cecton) [reply apollo-router-core/src/spec/field_type.rs]: SO! As discussed I'm not too much into renaming to a method prefixed with `is_` because they are usually low-cost methods that consult something. I decided to replace the bool with results. It's a bit les mumbo jumbo with the bool expression but a bit more into collecting Result.

Let me know if you don't like either and I will just rename validate_value is is_value_valid

Fixed in 10e3e17

File: apollo-router-core/src/spec/query.rs (hunk 2 above)
Comment (cecton) [reply apollo-router-core/src/spec/query.rs:30]: It's kinda the atomic operation here already as the `ResponseStream` yields `Reponse`s and this function applies on a single `Response`.

Since there is no IO or wait on network or something, this function has nothing to "await" for, so it needs to be blocking. Though a caller could probably use tokio::spawn_blocking if they do notice the processing is taking too long.

There might be also a case to make about limiting the size of this so it doesn't block the entire application indefinitely when the payload is unreasonably big. Though I suspect we might want to do that on the request first or everywhere there is JSON parsing... I'm not sure how serde handles limit in payload. Maybe we should limit the query size in bytes? And response size from the subgraphs?

File: apollo-router/src/lib.rs (hunk 7 above)
Comment (cecton) [reply apollo-router/src/lib.rs:77]: yeah and tbh I'm not sure which ones can be ignored. It's not like we instantiate those objects a lot or "372 bytes" is such a big deal :confounded: really in doubt here so I followed clippy's advice which might be wrong

File: apollo-router-core/src/spec/field_type.rs (hunk 5 above)
Comment (cecton) [reply apollo-router-core/src/spec/field_type.rs]: Fixed in e42d107

I kept `is_f64()` for the float type and I use `is_i64() || is_u64()` for the integer type. I think that makes more sense right?

**Comment by cecton** [comment]
OH NOW WE HAVE SCORES!! 

Mine: 7287
main: 7195

Wait... this is still wrong XD this PR should be slower....

File: apollo-router-core/src/spec/field_type.rs [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+    NonNull(Box<FieldType>),
+    String,
+    Int,
+    Float,
+    Id,
+    Boolean,
+}
+
+impl FieldType {
+    pub(crate) fn validate_value(
```
Comment (BrynCooke) [inline apollo-router-core/src/spec/field_type.rs:21]: Float, Integer and Bool can be represented as strings, so coercion supported need to be added. Can be a followup ticket though.

**Review by BrynCooke — APPROVED** [review]
Minor issues around validation logic, but otherwise looks good.

File: apollo-router-core/src/spec/field_type.rs [hunk 10]
```diff
@@ -0,0 +1,119 @@
...
+        &self,
+        value: &Value,
+        schema: &Schema,
+    ) -> Result<(), InvalidValue> {
+        match (self, value) {
+            (FieldType::String, Value::String(_)) => Ok(()),
+            (FieldType::Int, Value::Number(number)) if number.is_i64() || number.is_u64() => Ok(()),
```
[the remark this answers is not in the document]
Comment (cecton) [reply apollo-router-core/src/spec/field_type.rs:28]: oh god really

File: apollo-router-core/src/spec/field_type.rs (hunk 9 above)
Comment (cecton) [reply apollo-router-core/src/spec/field_type.rs:21]: what, where did you see that? oh that would explain what i saw with the ID type

**Review by garypen — COMMENTED** [review]
Let me know what you think about the question I have on FieldTypes. Apart from that, looks good!

**Comment by garypen** [comment]
> OH NOW WE HAVE SCORES!!
> 
> Mine: 7287 main: 7195
> 
> Wait... this is still wrong XD this PR should be slower....

I think there is "variation" in the benchmarking system due to "noisy neighbours" in the cloud and other source of variance.

File: apollo-router-core/src/error.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (garypen) [reply apollo-router-core/src/error.rs:248]: Github lost my comment here. I'll repeat it. I like match guards for this kind of thing as a bit clearer:
```
        match LevelFilter::current() {
            LevelFilter::OFF => {
                return;
            }
            _ if atty::is(atty::Stream::Stdout) => {
                // Fancy Miette reports for TTYs
                self.errors.iter().for_each(|err| {
                    let report = Report::new(ParserError {
                        src: NamedSource::new("supergraph_schema", self.raw_schema.clone()),
                        span: (err.index(), err.data().len()).into(),
                        ty: err.message().into(),
                    });
                    println!("{:?}", report);
                });
            }
            _ => {
                // Best effort to display errors
                self.errors.iter().for_each(|r| {
                    println!("{:#?}", r);
                });
            }
        }
```

File: apollo-router-core/src/spec/field_type.rs [hunk 11]
```diff
@@ -0,0 +1,119 @@
...
+            (FieldType::Float, Value::Number(number)) if number.is_f64() => Ok(()),
+            // "The ID scalar type represents a unique identifier, often used to refetch an object
+            // or as the key for a cache. The ID type is serialized in the same way as a String;
+            // however, it is not intended to be human-readable. While it is often numeric, it
+            // should always serialize as a String."
+            //
+            // In practice it seems Int works too
+            (FieldType::Id, Value::String(_) | Value::Number(_)) => Ok(()),
```
[the remark this answers is not in the document]
Comment (cecton) [reply apollo-router-core/src/spec/field_type.rs:36]: No I think it's the type coercion mentioned by Bryn there: https://github.com/apollographql/router/pull/227#discussion_r769520428

**Comment by cecton** [comment]
> I think there is "variation" in the benchmarking system due to "noisy neighbours" in the cloud and other source of variance.

Ah I restarted it and now I have 6912... which seems to low

File: apollo-router-core/src/spec/field_type.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (cecton) [reply apollo-router-core/src/spec/field_type.rs]: Fixed in 91d51fba42b10b5f0ea4ee9ca7ee1a3eba396e7e

File: apollo-router-core/src/query_cache.rs [hunk 12]
```diff
@@ -9,17 +9,12 @@ pub struct QueryCache {
...
+struct QueryCacheResolver;
 
 #[async_trait::async_trait]
 impl CacheResolver<String, Option<Arc<Query>>> for QueryCacheResolver {
     async fn retrieve(&self, key: String) -> Result<Option<Arc<Query>>, CacheResolverError> {
-        let query_parsing_future = {
-            let schema = Arc::clone(&self.schema);
-            tokio::task::spawn_blocking(move || Query::parse(key, &schema))
-        };
+        let query_parsing_future = tokio::task::spawn_blocking(move || Query::parse(key));
```
[the remark this answers is not in the document]
Comment (cecton) [reply apollo-router-core/src/query_cache.rs]: Fixed in 693c65dd8154534eb9a888fd08315e4efdc43f6d

File: apollo-router-core/src/spec/field_type.rs (hunk 9 above)
Comment (cecton) [reply apollo-router-core/src/spec/field_type.rs:21]: Fixed in 41e2279c82635167523d7aa2768caf40ff69fcc2

File: apollo-router-core/src/error.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (cecton) [reply apollo-router-core/src/error.rs:248]: yup and in that case we can remove the `return`! Nice :heart: @o0Ignition0o do you like it too?

File: apollo-router-core/src/spec/query.rs (hunk 8 above)
Comment (cecton) [reply apollo-router-core/src/spec/query.rs:228]: The panic is only when you activate the feature failfast. No panic if you use log level debug without failfast

Comment (cecton) [reply apollo-router-core/src/spec/query.rs:228]: https://github.com/apollographql/router/blob/13045c514ec9954f2c3713999c31b4b75fa805e9/apollo-router-core/src/lib.rs#L3-L12

File: apollo-router-core/src/spec/field_type.rs (hunk 5 above)
Comment (Geal) [reply apollo-router-core/src/spec/field_type.rs]: :+1:

File: apollo-router/src/lib.rs (hunk 7 above)
Comment (Geal) [reply apollo-router/src/lib.rs:77]: I am not a fan of adding a Box everywhere for this, and I know we can tell clippy to ignore that one, but I do not care too much about having it either way

File: apollo-router-core/src/spec/query.rs (hunk 8 above)
Comment (Geal) [reply apollo-router-core/src/spec/query.rs:228]: alright, I see now, thanks

**Comment by Geal** [comment]
> Ah I restarted it and now I have 6912... which seems to low

no need to worry too much for a 5% difference. Panic when it's larger than 20% :smile:

File: apollo-router/src/lib.rs (hunk 7 above)
Comment (cecton) [reply apollo-router/src/lib.rs:77]: Same... I think that will be for a future refactoring of the state_machine.rs at some point
