### PR TITLE
fix: osx file reload

### LINKED ISSUE #60: Hot reloading (file watching) probably does not work on OSX
While working on the release workflow I had to ignore some tests for OSX because they were not working. I believe it is possible the hot reloading of the configuration and schema is not working on OSX.

cc @BrynCooke

### PR DESCRIPTION
**Pull request by o0Ignition0o**
fixes #60 

As explained in the [notify documentation](https://github.com/notify-rs/notify/blob/ded07f442a96f33c6b7fefe3195396a33a28ddc3/src/lib.rs#L413) the file Create event has a higher priority than the Write event.

However our tests create the file and almost immediately start writing to it. The watcher did not propagate Create events, which lead to flakiness in these tests.

I'm lacking context but given the  `tokio::time::sleep()`s in the tests, this issue might have been seen on Linux as well, and worked around.

This commit removes the sleep()s in the test write functions, allows us to listen to Create events as well as Write events, and re enables the tests on osx.

### CODE REVIEW

File: crates/apollo-router/src/files.rs [hunk 1]
```diff
@@ -50,21 +63,18 @@ pub(crate) mod tests {
...
-    #[cfg(not(target_os = "macos"))]
     use test_log::test;
 
-    #[cfg(not(target_os = "macos"))]
     #[test(tokio::test)]
     async fn basic_watch() {
         let (path, mut file) = create_temp_file();
         let mut watch = watch(path, Some(Duration::from_millis(10)));
-        watch.next().await;
+        // Signal telling us ot fetch the data.
```
Comment (o0Ignition0o) [inline crates/apollo-router/src/files.rs:72]:
```suggestion
        // Signal telling us to fetch the file data once.
```

**Review by cecton — APPROVED** [review]
Oh wow that was a tricky one. Good job
