### PR TITLE
fix: ExposeQueryPlan: Move the plugin code to execution_service

### LINKED ISSUE #1541: expose query plan only works on the first query
If I run the router (from `main` as of this issue 77621dd2a709a8dd8d4cbeb09bbf46fef50678ab) with the experimental feature in #1470 using the following config (using the starstuff getting started graph):

#### Config
```yaml
plugins:
  experimental.expose_query_plan: true
```

It starts up with this:

```
2022-08-18T17:33:20.231639Z  INFO apollo_router::router_factory: list of plugins plugin_details=[("apollo.csrf", "apollo_router::plugins::csrf::Csrf"), ("apollo.telemetry", "apollo_router::plugins::telemetry::Telemetry"), ("experimental.expose_query_plan", "apollo_router::plugins::expose_query_plan::ExposeQueryPlan")]
```

And then if I make this request:

#### Request

```sh
curl -s --request POST \
    --header 'Apollo-Expose-Query-Plan: true' \
    --header 'content-type: application/json' \
    --url 'http://127.0.0.1:4000/' \
    --data '{"query":"query QuesoMakesTheWorld {  topProducts {  reviews { author { username } } } me { reviews { product {  name } } } }"}'
```

It **successfully** returns:

```json5
{
  "data": { /* actual data */ },
  "extensions": {
    "apolloQueryPlan": {
      /*... with the full query plan */
    }
  }
}
```

However, if I run the query again after that (no matter how many times), it no longer returns the query plan and only returns the `data`:

```json5
{
  "data": { /* actual data */ }
  /* Look ma, no plan */
}
```

### PR DESCRIPTION
**Pull request by o0Ignition0o**
fixes https://github.com/apollographql/router/issues/1541, part of https://github.com/apollographql/router/issues/1545

This commit moves the ExposeQueryPlan behavior to the execution_service, while we're progressively removing query_planner_service from the api.

### CODE REVIEW

File: apollo-router/src/plugins/expose_query_plan.rs [hunk 1]
```diff
@@ -235,14 +220,21 @@ mod tests {
...
+        execute_supergraph_test(VALID_QUERY, &*EXPECTED_RESPONSE_WITH_QUERY_PLAN, router).await;
     }
 
     #[tokio::test]
     async fn it_doesnt_expose_query_plan() {
         let plugin = get_plugin(&serde_json::json!(false)).await;
-        let router = build_mock_router(plugin).await;
-        execute_router_test(VALID_QUERY, &*EXPECTED_RESPONSE_WITHOUT_QUERY_PLAN, router).await;
+        let router = build_mock_supergraph(plugin).await;
+        execute_supergraph_test(VALID_QUERY, &*EXPECTED_RESPONSE_WITHOUT_QUERY_PLAN, router).await;
```
Comment (garypen) [inline apollo-router/src/plugins/expose_query_plan.rs:238]:
```suggestion
        let supergraph = build_mock_supergraph(plugin).await;
        execute_supergraph_test(VALID_QUERY, &*EXPECTED_RESPONSE_WITHOUT_QUERY_PLAN, supergraph).await;
```

File: apollo-router/src/plugins/expose_query_plan.rs [hunk 2]
```diff
@@ -235,14 +220,21 @@ mod tests {
...
-        execute_router_test(VALID_QUERY, &*EXPECTED_RESPONSE_WITH_QUERY_PLAN, router).await;
+        let router = build_mock_supergraph(plugin).await;
+        execute_supergraph_test(
+            VALID_QUERY,
+            &*EXPECTED_RESPONSE_WITH_QUERY_PLAN,
+            router.clone(),
+        )
+        .await;
+        // let's try that again
+        execute_supergraph_test(VALID_QUERY, &*EXPECTED_RESPONSE_WITH_QUERY_PLAN, router).await;
```
Comment (garypen) [inline apollo-router/src/plugins/expose_query_plan.rs:231]:
```suggestion
        let supergraph = build_mock_supergraph(plugin).await;
        execute_supergraph_test(
            VALID_QUERY,
            &*EXPECTED_RESPONSE_WITH_QUERY_PLAN,
            supergraph.clone(),
        )
        .await;
        // let's try that again
        execute_supergraph_test(VALID_QUERY, &*EXPECTED_RESPONSE_WITH_QUERY_PLAN, supergraph).await;
```

**Review by garypen — APPROVED** [review]
Looks good. I've put in a couple of NIT suggestions for renaming variables.

File: apollo-router/src/plugins/expose_query_plan.rs (hunk 1 above)
Comment (o0Ignition0o) [reply apollo-router/src/plugins/expose_query_plan.rs:238]: good catch!

File: apollo-router/src/plugins/expose_query_plan.rs (hunk 2 above)
Comment (o0Ignition0o) [reply apollo-router/src/plugins/expose_query_plan.rs]: fixed in bba9aa68

File: apollo-router/src/plugins/expose_query_plan.rs (hunk 1 above)
Comment (o0Ignition0o) [reply apollo-router/src/plugins/expose_query_plan.rs]: fixed in bba9aa68

**Review by Geal — APPROVED** [review]
