### PR TITLE
measure router processing time

### LINKED ISSUE #1949: Metric to quantify router overhead
Customers often ask how much time is pure router overhead. I'm not exactly sure how that would be calculated, as it's not as simple as `(total_time - sum(subgraph_fetch_time))` because fetches can happen in parallel. Is there a way to find the amount of time in a span *not* spent in child spans? 

Essentially, I want the time marked with `*` in this diagram as a Prometheus metric: 

```
 **            *                ***                      ***
|-----------------------------------------------------------|
   |----------|   
                |--------------|
                |----------|
                                   |--------------------| 
```

This would allow graph platform teams to discover Router regressions after upgrades or after changing configuration.

### LINKED ISSUE #2057: provide explicit metric for internal router latency
We need the ability to accurately report and attribute latency within our Federated ecosystem to internal Router latency and Subgraph request latency. 

We'd like a prometheus metric designed to capture this explicitly.

We've discussed trying to back out subgraph latency metrics from supergraph latency metrics but issues surrounding truly federated queries across multiple subgraphs can lead to confusing results.

### PR DESCRIPTION
**Pull request by Geal**
- Fix #1949 
- Fix #2057

This adds a new metric called `apollo_router_processing_time` that measures the time spent executing the request  minus the time spent waiting for an external request (subgraph request or external plugin).

This is not a perfect metric, as there are cases where the router's processing time can happen during another subgraph request, and ultimately shift some spans. Nevertheless, this should provide a good approximation.

### CODE REVIEW

File: apollo-router/src/axum_factory/axum_http_server_factory.rs [hunk 1]
```diff
@@ -329,7 +329,14 @@ async fn handle_graphql(
     service: router::BoxService,
     http_request: Request<Body>,
 ) -> impl IntoResponse {
-    match service.oneshot(http_request.into()).await {
+    let request: router::Request = http_request.into();
+    let context = request.context.clone();
+
+    let res = service.oneshot(request).await;
+    let overhead_seconds = (context.busy_timer.lock().await.current() / 1000_000_000) as f64;
+    tracing::info!(histogram.apollo_router_overhead_time = overhead_seconds,);
```
Comment (smyrick) [inline apollo-router/src/axum_factory/axum_http_server_factory.rs:337]: To reflect the caveat better, should we call this `apollo_router_internal_execution_time` or `apollo_router_processing_time` or something along those lines?

Comment (Geal) [reply apollo-router/src/axum_factory/axum_http_server_factory.rs]: processing time sounds good, updated in [a7c30fd](https://github.com/apollographql/router/pull/2371/commits/a7c30fdfe4e35992068038752d2ed818d403dce6)

File: docs/source/configuration/metrics.mdx [hunk 2]
```diff
@@ -65,6 +65,7 @@ The following metrics are available using Prometheus:
 - Number of cache misses for different `kind` of cache (`apq`, `query planner`, `introspection`) and for different `storage` (`memory`, `redis`): `apollo_router_cache_miss_count`
 - Time to hit the cache for different `kind` of cache (`apq`, `query planner`, `introspection`) and for different `storage` (`memory`, `redis`): `apollo_router_cache_hit_time`
 - Time to miss the cache for different `kind` of cache (`apq`, `query planner`, `introspection`) and for different `storage` (`memory`, `redis`): `apollo_router_cache_miss_time`
+- Time spent processing a request, outside of waiting for external or subgraph requests (`apollo_router_processing_time`)
```
Comment (bnjjj) [inline docs/source/configuration/metrics.mdx:68]: Could you add info to indicate the unit is in seconds please ?

Comment (Geal) [reply docs/source/configuration/metrics.mdx]: done in [7afe859](https://github.com/apollographql/router/pull/2371/commits/7afe859dc926c0a9ca9c4c74a293f0fa16b6516e)

File: docs/source/configuration/metrics.mdx [hunk 3]
```diff
@@ -63,8 +63,9 @@ The following metrics are available using Prometheus:
...
 - Number of cache misses for different `kind` of cache (`apq`, `query planner`, `introspection`) and for different `storage` (`memory`, `redis`): `apollo_router_cache_miss_count`
-- Time to hit the cache for different `kind` of cache (`apq`, `query planner`, `introspection`) and for different `storage` (`memory`, `redis`): `apollo_router_cache_hit_time`
-- Time to miss the cache for different `kind` of cache (`apq`, `query planner`, `introspection`) and for different `storage` (`memory`, `redis`): `apollo_router_cache_miss_time`
+- Time to hit the cache for different `kind` of cache (`apq`, `query planner`, `introspection`) and for different `storage` (`memory`, `redis`), in seconds: `apollo_router_cache_hit_time`
+- Time to miss the cache for different `kind` of cache (`apq`, `query planner`, `introspection`) and for different `storage` (`memory`, `redis`), in seconds: `apollo_router_cache_miss_time`
+- Time spent processing a request, outside of waiting for external or subgraph requests, in seconds (`apollo_router_processing_time`)
```
Comment (garypen) [inline docs/source/configuration/metrics.mdx:68]: Seconds seems an odd choice for this measure. I think MilliSeconds would be more natural. What's the reason for choosing seconds? Is there a convention for this kind of thing?

File: NEXT_CHANGELOG.md [hunk 4]
```diff
@@ -137,6 +137,12 @@ supergraph:
 
 By [@Geal](https://github.com/geal) in https://github.com/apollographql/router/pull/2386
 
+### Measure the router's processing time ([Issue #1949](https://github.com/apollographql/router/issues/1949) [Issue #2057](https://github.com/apollographql/router/issues/2057))
+
+There is a new metric called `apollo_router_processing_time` that measures the time spent executing the request minus the time spent waiting for an external request (subgraph request or external plugin). This accounts both for the time spent actually executing on the request, and the time spent waiting for concurrent client requests to be executed.
```
Comment (garypen) [inline NEXT_CHANGELOG.md:142]: Should specify the units of the new metric.

File: apollo-router/src/axum_factory/axum_http_server_factory.rs [hunk 5]
```diff
@@ -329,7 +329,16 @@ async fn handle_graphql(
     service: router::BoxService,
     http_request: Request<Body>,
 ) -> impl IntoResponse {
-    match service.oneshot(http_request.into()).await {
+    let request: router::Request = http_request.into();
+    let context = request.context.clone();
+
+    let res = service.oneshot(request).await;
+    let dur = context.busy_time_ns().await;
+    let processing_seconds = dur as f64 / 1_000_000_000f64;
```
Comment (garypen) [inline apollo-router/src/axum_factory/axum_http_server_factory.rs:337]: NIT Presumably not returning a duration because it would be higher overhead... If not using duration we could have inline function on BusyTime that does the calculation.

As noted elsewhere, I wonder if "seconds" is the correct unit here.

File: apollo-router/src/context.rs [hunk 6]
```diff
@@ -38,6 +39,9 @@ pub struct Context {
     #[serde(skip)]
     #[serde(default = "Instant::now")]
     pub(crate) created_at: Instant,
+
+    #[serde(skip)]
+    busy_timer: Arc<Mutex<BusyTimer>>,
```
Comment (garypen) [inline apollo-router/src/context.rs:44]: Is the `Mutex` avoidable? Atomics...

**Review by garypen — COMMENTED** [review]
I think there is a lot of good content here, but I've got some simple questions about units and I wonder if we can avoid introducing the Mutex.

File: docs/source/configuration/metrics.mdx (hunk 3 above)
Comment (Geal) [reply docs/source/configuration/metrics.mdx:68]: for consistency: we use seconds in other places too, and anyway the value is a float. (Personally I would have gone with milliseconds everywhere)

File: NEXT_CHANGELOG.md (hunk 4 above)
Comment (Geal) [reply NEXT_CHANGELOG.md]: added in 4bd28508

File: apollo-router/src/axum_factory/axum_http_server_factory.rs (hunk 5 above)
Comment (Geal) [reply apollo-router/src/axum_factory/axum_http_server_factory.rs:337]: good point, `Duration` has the[as_secs_f64](https://doc.rust-lang.org/stable/std/time/struct.Duration.html#method.as_secs_f64) method

File: apollo-router/src/context.rs (hunk 6 above)
Comment (Geal) [reply apollo-router/src/context.rs:44]: I wanted to go with atomics first, but having to set the `start` field complicates it. At least this could be simplified by using a parking lot mutex instead of a futures aware mutex

File: apollo-router/src/axum_factory/axum_http_server_factory.rs (hunk 5 above)
Comment (Geal) [reply apollo-router/src/axum_factory/axum_http_server_factory.rs]: fixed in 9804f0db

File: apollo-router/src/context.rs (hunk 6 above)
Comment (Geal) [reply apollo-router/src/context.rs:45]: as a side note, I'd like to review our uses of mutexes, and see which ones could move away from futures aware locks,  it might be faster [as outlined here](https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use). I pushed hard for removing a lot of them and moving towards futures mutex in the past because we had locks all over the place, but now that the code is much more stable, this is something we can revisit

**Review by garypen — APPROVED** [review]
