### PR TITLE
delete router_url config for subgraphs in the config file #522

### LINKED ISSUE #522: Cannot use managed federation and layers together without specifying `router_url`
**Describe the bug**
Run the router with the environment variables `APOLLO_GRAPH_REF` and `APOLLO_KEY` such as to use managed federation that's setup in apollo studio. Also provide a configuration file so as to use layers and `headers_propagate` but don't set the `routing_url` as that comes from managed federation.

Running the router results in 
> Failed to read configuration: Could not deserialize configuration: subgraphs.user: missing field `routing_url` at line 12 column 11

**To Reproduce**
1. Set `APOLLO_GRAPH_REF` and `APOLLO_KEY` to appropriate values for your federated graph within apollo studio
1. Add layer configuration within configuration file to propagate headers but don't set `routing_url`
1. Run router with the flag `--configuration` pointing to a local configuration file
1. See error as described above

**Expected behavior**
Able to use apollo studio managed federation and it's configuration for routing urls but add layers for header propagation as well in the router without needing to specify the subgraph url

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.0.1

**Router version
- router 0.1.0-alpha.6

### PR DESCRIPTION
**Pull request by bnjjj**
close #522

### CODE REVIEW

**Review by Geal — APPROVED** [review]

**Comment by bnjjj** [comment]
Perf test please

**Comment by bnjjj** [comment]
Perf test please

**Comment by bnjjj** [comment]
Ok I need to add support of overriding of the URL through a plugin in order to keep the performance test working

File: apollo-router/src/plugins/override_url.rs [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+                }
+
+                req
+            })
+            .boxed()
+    }
+}
+
+register_plugin!(
+    "com.apollographql",
```
Comment (BrynCooke) [inline apollo-router/src/plugins/override_url.rs:44]: Let's leave the group blank for our plugins. We're core.

**Review by BrynCooke — APPROVED** [review]
Approved pending the change around the plugin group.

File: apollo-router/src/plugins/override_url.rs (hunk 1 above)
Comment (bnjjj) [reply apollo-router/src/plugins/override_url.rs:44]: Ok that's was also my feeling and then I looked up for the `reporting` plugin. I think it could be worth to do the same for `reporting` plugin.

**Comment by bnjjj** [comment]
Perf test please

File: apollo-router/src/plugins/override_url.rs (hunk 1 above)
Comment (BrynCooke) [reply apollo-router/src/plugins/override_url.rs]: Agreed

**Comment by bnjjj** [comment]
Perf test please

File: apollo-router/src/plugins/override_url.rs (hunk 1 above)
Comment (o0Ignition0o) [reply apollo-router/src/plugins/override_url.rs]: As @garypen rightfully pointed out [in this comment](https://github.com/apollographql/router/pull/532#discussion_r819401449) we definitely want an ADR about the naming convention

Comment (o0Ignition0o) [reply apollo-router/src/plugins/override_url.rs]: opened https://github.com/apollographql/router/issues/581

**Comment by bnjjj** [comment]
Perf test please

**Review by Geal — APPROVED** [review]
