### PR TITLE
fix: return valid GraphQL responses for invalid requests

### LINKED ISSUE #2934: bug: invalid GraphQL response on a POST with no body
to reproduce

terminal 1:

```console
$ cd ./examples/hello-world/rust
$ cargo run -- -c ./router.yaml -s ../../graphql/local.graphql
```

terminal 2:

```console
$ curl -X POST -H "content-type: application/json" http://127.0.0.1:4000 | jq
{
  "message": "Invalid GraphQL request",
  "extensions": {
    "details": "failed to deserialize the request body into JSON: EOF while parsing a value at line 1 column 0",
    "code": "INVALID_GRAPHQL_REQUEST"
  }
}
```

The error message here is fine, but the error message is not nested under a top level `errors` field. Behavior I would expect here:

```console
$ curl -X POST -H "content-type: application/json" http://127.0.0.1:4000 | jq
{
  "data": null,
  "errors": [
    {
      "message": "Invalid GraphQL request",
      "extensions": {
        "details": "failed to deserialize the request body into JSON: EOF while parsing a value at line 1 column 0",
        "code": "INVALID_GRAPHQL_REQUEST"
      }
    }
  ]
}
```

### LINKED ISSUE #2946: bug: invalid GraphQL response on bad content type header
to reproduce

terminal 1:

```console
$ cd ./examples/hello-world/rust
$ cargo run -- -c ./router.yaml -s ../../graphql/local.graphql
```

terminal 2:

```console
$ curl --data '{ "query": "query { __typename }"' -H "content-type: garbage" http://127.0.0.1:4000 | jq
{
  "message": "'content-type' header can't be different from \"application/json\" or \"application/graphql-response+json\"",
    "extensions": {
    "code": "INVALID_CONTENT_TYPE_HEADER"
  }
}
```

The error message here is fine, but the error message is not nested under a top level `errors` field, and the code is `INVALID_ACCEPT_HEADER` instead of `INVALID_CONTENT_TYPE_HEADER`. Behavior I would expect here:

```console
$ curl --data '{ "query": "query { __typename }"' -H "content-type: garbage" http://127.0.0.1:4000 | jq
{
  "errors": [
    {
      "message": "'content-type' header can't be different from \"application/json\" or \"application/graphql-response+json\"",
      "extensions": {
        "code": "INVALID_CONTENT_TYPE_HEADER"
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by EverlastingBugstopper**
This PR fixes a few cases where the router returns GraphQL errors directly rather than nesting them under a top level `errors` array.

Fixes #2934
Fixes #2946

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [x] Changes are compatible[^1]
~- [ ] Documentation[^2] completed~
~- [ ] Performance impact assessed and acceptable~
- Tests added and passing[^3]
    - [x] Unit Tests
    - [x] Integration Tests
    - [x] Manual Tests

**Exceptions**

No documentation needs to be updated because these are bugs. Performance should not be impacted because we are just constructing a slightly different response.

### CODE REVIEW

**Review by o0Ignition0o — APPROVED** [review]

File: apollo-router/src/services/layers/content_negociation.rs [hunk 1]
```diff
@@ -55,19 +55,18 @@ where
...
-                                        .build(),
-                                )
-                                .unwrap_or_else(|_| String::from("Invalid request"))
-                        ))
-                        .expect("cannot fail");
+                                serde_json::json!({
+                                    "errors": [
+                                        graphql::Error::builder()
+                                            .message(format!(
+                                                r#"'content-type' header can't be different from {:?} or {:?}"#,
```
Comment (BrynCooke) [inline apollo-router/src/services/layers/content_negociation.rs:62]:
```suggestion
                                                r#"'content-type' header must be one of: {:?} or {:?}"#,
```

**Review by BrynCooke — APPROVED** [review]
LGTM.
Suggestion for changing the error message slightly, but this could be tackled separately.

File: .changesets/fix_avery_fix_invalid_graphql_response.md [hunk 2]
```diff
@@ -0,0 +1,7 @@
+### fix: return valid GraphQL responses for invalid requests ([Issue #2934](https://github.com/apollographql/router/issues/2934)), ([Issue #2946](https://github.com/apollographql/router/issues/2946))
+
+This PR fixes the way the router handles invalid requests. The router now returns GraphQL errors nested under a top level `errors` array rather than returning a single GraphQL error JSON object.
+
+A new error code has been introduced: "INVALID_CONTENT_TYPE_HEADER". Older versions of the router returned "INVALID_ACCEPT_HEADER" when an invalid content type header was sent.
+
+By [@EverlastingBugstopper](https://github.com/EverlastingBugstopper) in https://github.com/apollographql/router/pull/2947
```
Comment (abernix) [inline .changesets/fix_avery_fix_invalid_graphql_response.md:7]:
```suggestion
### Invalid requests now return proper GraphQL-shaped errors ([Issue #2934](https://github.com/apollographql/router/issues/2934)), ([Issue #2946](https://github.com/apollographql/router/issues/2946))

Certain invalid HTTP requests — such as when an unacceptable `content-type` header, or an unsupported `accept` header are received — now return proper GraphQL errors nested as elements in a top-level `errors` array, rather than returning a single GraphQL error JSON object, which was unintentional.

This also brought the introduction of a more correct error code, `INVALID_CONTENT_TYPE_HEADER`, rather than using `INVALID_ACCEPT_HEADER` when an invalid content type header was received.

By [@EverlastingBugstopper](https://github.com/EverlastingBugstopper) in https://github.com/apollographql/router/pull/2947
```

**Review by abernix — APPROVED** [review]

**Comment by abernix** [comment]
Thanks, @EverlastingBugstopper! Auto-squash enabled.

**Comment by abernix** [comment]
Looks like some on-going test failures on existing assertions because the message changes, e.g. on `it_send_bad_content_type`

**Comment by EverlastingBugstopper** [comment]
absolutely - thought i fixed it up but forgot to add the `:`
