### PR TITLE
Make all `apollo_router_http_requests_total` metrics match

### LINKED ISSUE #4047: `OpenTelemetry metric error occurred` error log
**Describe the bug**
In the log, the following event is emitted:
```
OpenTelemetry metric error occurred: Metrics error: Instrument description conflict, using existing. Instrument apollo_router_http_requests_total_total, Existing: "Total number of HTTP requests made.", dropped: ""
```

**To Reproduce**
Running the router

**Expected behavior**
No log

**Desktop (please complete the following information):**
 - Version: 1.32.0

### PR DESCRIPTION
**Pull request by BrynCooke**
Metrics definitions must match, including descriptions.

Currently we have the same metric scattered across the codebase. This is not ideal, but we are refactoring metrics callsites. 
In the meantime, let's just make things match so that users don't see an error in the logs.

I tries to pull stuff out to consts, but I don't think this is possible without changing the macros, and we don't actually want people to have multiple callsites for metrics. The golden rule is one metric one callsite.

Fixes #4047

### CODE REVIEW

File: apollo-router/src/plugins/telemetry/mod.rs [hunk 1]
```diff
@@ -1776,6 +1776,13 @@ fn handle_error_internal<T: Into<opentelemetry::global::Error>>(
     #[cfg(test)]
     let threshold = Duration::from_millis(100);
 
+    // For now we have to suppress Metrics error: reader is shut down or not registered
```
Comment (BrynCooke) [inline apollo-router/src/plugins/telemetry/mod.rs:1779]: The reason that this had to move was that we do need to be able to see useful metrics errors, and this was suppressing them.

**Review by o0Ignition0o — APPROVED** [review]
LGTM!

**Review by bnjjj — APPROVED** [review]

File: .changesets/fix_bryn_prom_differing_descriptions.md [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+
+The Router emitted identical metrics events with different descriptions causing an error to be emitted to the logs.
+
+```log
+OpenTelemetry metric error occurred: Metrics error: Instrument description conflict, using existing.
+```
+
+The metrics description have been brought into alignment.
+
+By [@BrynCooke](https://github.com/BrynCooke) in https://github.com/apollographql/router/pull/4065
```
Comment (abernix) [inline .changesets/fix_bryn_prom_differing_descriptions.md:11]:
```suggestion
### Ensure `apollo_router_http_requests_total` metrics match ([Issue #4047](https://github.com/apollographql/router/issues/4047))

Identically _named_ metrics were being emitted for `apollo_router_http_requests_total` (as intended) but with different _descriptions_ (not intended) resulting in occasional, but noisy, log warnings:

```
OpenTelemetry metric error occurred: Metrics error: Instrument description conflict, using existing.
```

The metrics' descriptions have been brought into alignment to resolve the log warnings and we will follow-up with additional work to think holistically about a more durable pattern that will prevent this from occurring in the future.

By [@BrynCooke](https://github.com/BrynCooke) in https://github.com/apollographql/router/pull/4065
```
