### PR TITLE
Fix error handling for subgraphs

### LINKED ISSUE #3141: Subgraphs returning 401 error codes not being treated as errors by router
**Describe the bug**
When a subgraph service returns a 401 (or similar error codes) to the router it does not create a `SUBREQUEST_HTTP_ERROR` if the subgraph also returns `Content-Type: application/json`

**To Reproduce**
1. Setup [api-gateway-test.zip](https://github.com/apollographql/router/files/11564797/api-gateway-test.zip) by running `npm install` followed by `npm start`. This will run a server on `http://localhost:3000`
2. Run a router such that any of the subgraphs now points to `http://localhost:3000` and run a query against router that will cause that subgraph to be called.
3. Router should return
```
{
  "data": {}
}
```
4. Now, in the `api-gateway-test` directory open `/routes/index.js` and comment out the `res.setHeader('Content-Type', 'application/json');` line. The server will now return `Content-Type: text/html`. Restart the server.
5. Run the same query as before against the router, it should now return (assuming the router is not configured to forward subgraph errors):
```
{
  "data": {},
  "errors": [
    {
      "message": "HTTP fetch failed from 'redacted': redacted",
      "path": [],
      "extensions": {
        "code": "SUBREQUEST_HTTP_ERROR",
        "service": "redacted",
        "reason": "redacted"
      }
    }
  ]
}
```

**Expected behavior**
Router will return the `SUBREQUEST_HTTP_ERROR` as above in all situations where a 401 or similar error is thrown by the subgraph service.

**Additional context**
This was discovered when an API Gateway in front of a subgraph service threw 401 errors which were not getting back to the client.

### PR DESCRIPTION
**Pull request by BrynCooke**
The graphql spec is lax about what strategy to use for processing responses: https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#processing-the-response

> If the response uses a non-200 status code and the media type of the response payload is application/json
then the client MUST NOT rely on the body to be a well-formed GraphQL response since the source of the response
may not be the server but instead some intermediary such as API gateways, proxies, firewalls, etc.

The TLDR of this is that it's really asking us to do the best we can with whatever information we have with some modifications depending on content type.
Our goal is to give the user the most relevant information possible in the response errors

Rules:
1. If the content type of the response is not `application/json` or `application/graphql-response+json` then we won't try to parse.
2. If an HTTP status is not 2xx it will always be attached as a graphql error.
3. If the response type is `application/json` and status is not 2xx and the body is not valid grapqhql then parse errors will be suppressed.

Rule `#3` Is definitely up for debate.
> If the response type is application/json and status is not 2xx and the body is not valid grapqhql then parse errors will be suppressed.

Alternative are that:
* an error is attached with the entire contents of the response.
* the response is logged as a WARN.

Fixes #3141

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [x] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [x] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

### CODE REVIEW

**Comment by BrynCooke** [comment]
Note to reviewers. I think the unit tests need refactoring to make them dry, but I haven't got the time to do this right now.
I have just used the existing pattern.

File: apollo-router/src/services/subgraph_service.rs [hunk 1]
```diff
@@ -597,104 +593,205 @@ async fn call_http(
...
-            graphql::Response::from_bytes(&cloned_service_name, body).map_err(|error| {
-                FetchError::SubrequestMalformedResponse {
-                    service: cloned_service_name.clone(),
-                    reason: error.to_string(),
-                }
+    let resp = http::Response::from_parts(parts, graphql);
+    Ok(SubgraphResponse::new_from_response(resp, context))
+}
+
+async fn perform_fetch(
```
Comment (Geal) [inline apollo-router/src/services/subgraph_service.rs:737]: it's way simpler with all of the networking isolated there :+1:

File: apollo-router/src/services/subgraph_service.rs [hunk 2]
```diff
@@ -597,104 +593,205 @@ async fn call_http(
...
+                    tracing::error!(fetch_error = format!("{err:?}").as_str());
+                    Err(FetchError::SubrequestHttpError {
+                        status_code: None,
+                        service: service_name.to_string(),
+                        reason: err.to_string(),
+                    })
+                }
+                Ok(body) => Ok(body),
+            }
+        }
```
Comment (bnjjj) [inline apollo-router/src/services/subgraph_service.rs:791]: Can't we use a `map_err` for this ?

File: apollo-router/src/services/subgraph_service.rs [hunk 3]
```diff
@@ -597,104 +593,205 @@ async fn call_http(
...
+        Err(err) => {
+            tracing::error!(fetch_error = format!("{err:?}").as_str());
+            return Err(FetchError::SubrequestHttpError {
+                status_code: None,
+                service: service_name.to_string(),
+                reason: err.to_string(),
+            });
+        }
+        Ok(response) => response,
+    };
```
Comment (bnjjj) [inline apollo-router/src/services/subgraph_service.rs:752]: Can't we use a `map_err` ?

File: apollo-router/src/services/subgraph_service.rs [hunk 4]
```diff
@@ -597,104 +593,205 @@ async fn call_http(
...
-                }
-            }
-        }
+    // Perform the actual fetch. This
+    context.enter_active_request();
+    let (parts, body) = perform_fetch(client, service_name, request)
+        .instrument(subgraph_req_span)
+        .await
+        .map(|r| {
+            context.leave_active_request();
```
Comment (Geal) [inline apollo-router/src/services/subgraph_service.rs:628]: `leave_active_request` should be called on the error side too, otherwise it will count indefinitely.
I'll open a separate PR to move that accounting to a guard-like behaviour that stops counting when dropped, that will prevent some issues

File: apollo-router/src/services/subgraph_service.rs [hunk 5]
```diff
@@ -597,104 +593,205 @@ async fn call_http(
...
+    } else {
+        HttpStatus::Error
+    };
 
-        Ok((parts, body))
-    }.instrument(subgraph_req_span).await?;
+    let mut graphql: graphql::Response = match (content_type, http_status, body) {
+        (ContentType::ApplicationJson, HttpStatus::Error, Ok(bytes)) => {
+            graphql::Response::from_bytes(service_name, bytes)
+                .unwrap_or_else(|_error| graphql::Response::builder().build())
```
Comment (Geal) [inline apollo-router/src/services/subgraph_service.rs:684]: why not build an error response like `FetchError::SubrequestMalformedResponse` here? The status code is an error, and the content type was JSON yet we got a parse error, it looks like it warrants reporting an error

File: apollo-router/src/services/subgraph_service.rs [hunk 6]
```diff
@@ -597,104 +593,205 @@ async fn call_http(
...
+        }
+        Ok(response) => response,
+    };
+    // Keep our parts, we'll need them later
+    let (parts, body) = response.into_parts();
+
+    // Only try to get the body bytes if the content type was one of the accepted types
+    let body_bytes = match parts.headers.get(header::CONTENT_TYPE).map(|v| v.to_str()) {
+        Some(Ok(content_type))
+            if !content_type.contains(APPLICATION_JSON.essence_str())
```
Comment (Geal) [inline apollo-router/src/services/subgraph_service.rs:759]: converting the header value to a string and just looking for the presence of the substring is very fragile.

In other parts of the router we use the `mediatype` crate to parse those values:
https://github.com/apollographql/router/blob/dev/apollo-router/src/services/layers/content_negociation.rs#L191-L204

[By spec] (https://www.rfc-editor.org/rfc/rfc9110#field.content-type) the content-type header contains one media type

File: apollo-router/src/services/subgraph_service.rs [hunk 7]
```diff
@@ -597,104 +593,205 @@ async fn call_http(
...
+    // If the response uses a non-200 status code and the media type of the response payload is application/json then the client MUST NOT rely on the body to be a well-formed GraphQL response since the source of the response may not be the server but instead some intermediary such as API gateways, proxies, firewalls, etc.
 
-                }, Ok(body) => body,
-            };
+    enum ContentType {
+        ApplicationJson,
+        ApplicationGraphqlJson,
+        Other,
+    }
+    let content_type = parts
```
Comment (Geal) [inline apollo-router/src/services/subgraph_service.rs:656]: this was already extracted in `perform_fetch`, why not return it from that same function instead of looking at the header twice? That would avoid the `Other` element of the enum

**Review by Geal — CHANGES_REQUESTED** [review]

File: apollo-router/src/services/subgraph_service.rs (hunk 2 above)
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs]: [7534cc6](https://github.com/apollographql/router/pull/3328/commits/7534cc6607c769c903bd62590d9d5a0c2c338b4f)

File: apollo-router/src/services/subgraph_service.rs (hunk 3 above)
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs]: [7534cc6](https://github.com/apollographql/router/pull/3328/commits/7534cc6607c769c903bd62590d9d5a0c2c338b4f)

File: apollo-router/src/services/subgraph_service.rs (hunk 4 above)
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs]: [397a5b4](https://github.com/apollographql/router/pull/3328/commits/397a5b40ed5214987667ae4d2cc78f8b56685c6a)

File: apollo-router/src/services/subgraph_service.rs (hunk 5 above)
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs:684]: Yeah, this was the thing highlighted in the description.
The issue is that according to the spec it's "OK" for a subgraph response to be tampered with and return non-graphql if the content_type is `ApplicationJson`.
In this situation I'm tempted to say that if the response fails to parse then the error should contain the entire response rather than the parse error.

**Comment by o0Ignition0o** [comment]
As discussed this afternoon:

Subgraph errors (no data) when dealing with @requires:
- if the subgraph returns an error, we should not add more messages
- if the subgraph doesn't return any error, we should add a message.
Currently we return
 "Subgraph response from '{}' was missing key `_entities`"
we should make it "subgraph did not return a valid graphql response. (and possibly mention the need for entities or either data or errors)****

**Comment by glasser** [comment]
Would review from me still be helpful? Have been out since around when this was filed.

I'm not clear on what this means in the description:
> If an HTTP status is not 2xx it will always be attached as a graphql error.

Is this only for JSON responses? What gets attached as the error?

**Comment by BrynCooke** [comment]
@glasser I'm going to work on this today and then I think it's worth reviewing from scratch once it's ready (I'm going to take this back to draft). I'll add some extra comments to clarify things.

**Comment by BrynCooke** [comment]
> Would review from me still be helpful? Have been out since around when this was filed.
> 
> I'm not clear on what this means in the description:
> 
> > If an HTTP status is not 2xx it will always be attached as a graphql error.
> 
> Is this only for JSON responses? What gets attached as the error?

It'll be for all responses. Basically there will never be a situation where http is not success and there are no errors in the grapghql response.

File: apollo-router/src/services/subgraph_service.rs (hunk 5 above)
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs]: I've basically rewritten everything, so it needs to be reviewed from scratch.

File: apollo-router/src/services/subgraph_service.rs (hunk 7 above)
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs]: I've taken this into account in the rewrite.

File: apollo-router/src/services/subgraph_service.rs (hunk 6 above)
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs]: I've basically rewritten everything, so it needs to be reviewed from scratch.

**Comment by BrynCooke** [comment]
This has been rewritten, so people can take a look again. I think that I'll to the `_entities` thing as a separate PR now.

**Review by o0Ignition0o — CHANGES_REQUESTED** [review]

File: apollo-router/src/services/subgraph_service.rs [hunk 8]
```diff
@@ -297,10 +304,8 @@ impl tower::Service<SubgraphRequest> for SubgraphService {
 
                         // If not then put the subscription_id in the extensions for callback mode and continue
                         // Do this if the topic doesn't already exist
-                        let callback_url = public_url.join(&format!(
-                            "{}/{subscription_id}",
-                            path.as_deref().unwrap_or("/callback")
-                        ))?;
+                        let callback_url =
+                            public_url.join(&format!("/callback/{subscription_id}"))?;
```
Comment (o0Ignition0o) [inline apollo-router/src/services/subgraph_service.rs:308]: ok this looks like a merge fail.

**Comment by Geal** [comment]
refactoring the subgraph service was a good idea, but here it makes the review really hard to do when we look for the actual error handling changes :/

File: apollo-router/src/services/subgraph_service.rs [hunk 9]
```diff
@@ -602,100 +599,202 @@ async fn call_http(
...
+        Result<ContentType, FetchError>,
+        Option<Result<Bytes, FetchError>>,
+    ),
+    FetchError,
+> {
+    let _active_request_guard = context.enter_active_request();
+    let response = client
+        .call(request)
+        .map_err(|err| {
+            tracing::error!(fetch_error = format!("{err:?}").as_str());
```
Comment (bnjjj) [inline apollo-router/src/services/subgraph_service.rs:756]:
```suggestion
            tracing::error!(fetch_error = ?err);
```

File: apollo-router/src/services/subgraph_service.rs [hunk 10]
```diff
@@ -602,100 +599,202 @@ async fn call_http(
...
-            graphql::Response::from_bytes(&cloned_service_name, body).map_err(|error| {
-                FetchError::SubrequestMalformedResponse {
-                    service: cloned_service_name.clone(),
-                    reason: error.to_string(),
+    let body = if content_type.is_ok() {
+        let body = hyper::body::to_bytes(body)
+            .instrument(tracing::debug_span!("aggregate_response_data"))
+            .await
+            .map_err(|err| {
+                tracing::error!(fetch_error = format!("{err:?}").as_str());
```
Comment (bnjjj) [inline apollo-router/src/services/subgraph_service.rs:779]:
```suggestion
                tracing::error!(fetch_error = ?err);
```

File: apollo-router/src/services/subgraph_service.rs [hunk 11]
```diff
@@ -602,100 +599,202 @@ async fn call_http(
...
-            };
+enum ContentType {
+    ApplicationJson,
+    ApplicationGraphqlResponseJson,
+}
 
+fn content_type(service_name: &str, parts: &Parts) -> Result<ContentType, FetchError> {
+    match parts.headers.get(header::CONTENT_TYPE).map(|v| v.to_str().map(MediaType::parse)) {
+        Some(Ok(Ok(content_type)))if (content_type.ty == APPLICATION && content_type.subty == JSON) => Ok(ContentType::ApplicationJson),
+        Some(Ok(Ok(content_type)))if (content_type.ty == APPLICATION && content_type.subty == GRAPHQL_RESPONSE && content_type.suffix == Some(JSON)) => Ok(ContentType::ApplicationGraphqlResponseJson),
```
Comment (bnjjj) [inline apollo-router/src/services/subgraph_service.rs:718]: cargo fmt gave up

File: apollo-router/src/response.rs [hunk 12]
```diff
@@ -161,6 +161,15 @@ impl Response {
...
             None => vec![],
         };
+        // Graphql spec says:
+        // If the data entry in the response is not present, the errors entry in the response must not be empty.
+        // It must contain at least one error. The errors it contains should indicate why no data was able to be returned.
+        if (data.is_none()) && errors.is_empty() {
+            Err(FetchError::SubrequestMalformedResponse {
+                service: service_name.to_string(),
+                reason: "graphql response without data must contain at least one error".to_string(),
+            })?;
```
[the remark this answers is not in the document]
Comment (BrynCooke) [reply apollo-router/src/response.rs]: Fixed in #[709bb2e](https://github.com/apollographql/router/pull/3328/commits/709bb2ef0c1159c88991ea3917635c140f87fbfe)

File: apollo-router/src/services/subgraph_service.rs (hunk 11 above)
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs:723]: Yeah, I'm not sure why. The code doesn't look complicated.

File: apollo-router/src/services/subgraph_service.rs (hunk 8 above)
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs]: [ab60f8c](https://github.com/apollographql/router/pull/3328/commits/ab60f8c8017eba96c819c7f9c8e94f074c79892d)

File: apollo-router/src/services/subgraph_service.rs [hunk 13]
```diff
@@ -602,100 +604,205 @@ async fn call_http(
...
-                    };
+    // Print out the debug for the request
+    if display_headers {
+        tracing::info!(http.request.headers = ?request.headers(), apollo.subgraph.name = %service_name, "Request headers to subgraph {service_name:?}");
+    }
+    if display_body {
+        tracing::info!(http.request.body = ?request.body(), apollo.subgraph.name = %service_name, "Request body to subgraph {service_name:?}");
+    }
+
+    // Perform the actual fetch. I this fails then
```
Comment (o0Ignition0o) [inline apollo-router/src/services/subgraph_service.rs:633]: if this fails then ? ^^

File: apollo-router/src/services/subgraph_service.rs [hunk 14]
```diff
@@ -602,100 +604,205 @@ async fn call_http(
...
+}
 
-                }, Ok(body) => body,
-            };
+enum ContentType {
+    ApplicationJson,
+    ApplicationGraphqlResponseJson,
+}
 
+fn content_type(service_name: &str, parts: &Parts) -> Result<ContentType, FetchError> {
```
Comment (o0Ignition0o) [inline apollo-router/src/services/subgraph_service.rs:720]:
```suggestion
fn get_graphql_content_type(service_name: &str, parts: &Parts) -> Result<ContentType, FetchError> {
```

**Review by o0Ignition0o — APPROVED** [review]
looking great!

File: apollo-router/src/services/subgraph_service.rs (hunk 13 above)
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs]: [77ccb05](https://github.com/apollographql/router/pull/3328/commits/77ccb0577ba50ef3fe1b45d705fa12db7a58f9c8)

File: apollo-router/src/services/subgraph_service.rs (hunk 14 above)
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs]: [61a9a96](https://github.com/apollographql/router/pull/3328/commits/61a9a9623090bc339dd7e5c2451fc15dcd072d96)

File: apollo-router/src/services/subgraph_service.rs [hunk 15]
```diff
@@ -602,100 +604,205 @@ async fn call_http(
...
 
+fn get_graphql_content_type(service_name: &str, parts: &Parts) -> Result<ContentType, FetchError> {
+    let content_type = parts
+        .headers
+        .get(header::CONTENT_TYPE)
+        .map(|v| v.to_str().map(MediaType::parse));
+    match content_type {
+        Some(Ok(Ok(content_type))) if (content_type.ty == APPLICATION && content_type.subty == JSON) => Ok(ContentType::ApplicationJson),
+        Some(Ok(Ok(content_type))) if (content_type.ty == APPLICATION && content_type.subty == GRAPHQL_RESPONSE && content_type.suffix == Some(JSON)) => Ok(ContentType::ApplicationGraphqlResponseJson),
+        Some(Ok(Ok(content_type))) => {
```
Comment (Geal) [inline apollo-router/src/services/subgraph_service.rs:728]: nit: it may be more readable to match once on `Some(Ok(Ok(content_type)))` then have a nested match or branches on `content_type` fields

File: apollo-router/src/services/subgraph_service.rs [hunk 16]
```diff
@@ -945,6 +1052,85 @@ mod tests {
         server.await.unwrap();
     }
 
+    // starts a local server emulating a subgraph returning bad response format
+    async fn emulate_subgraph_ok_status_invalid_response(socket_addr: SocketAddr) {
```
Comment (Geal) [inline apollo-router/src/services/subgraph_service.rs:1056]: nit: instead of taking a (static) socket address as argument, that will end up conflicting with something else, this should open a listen socket on a random port and return the address

**Review by Geal — APPROVED** [review]

File: apollo-router/src/services/subgraph_service.rs [hunk 17]
```diff
@@ -602,100 +604,205 @@ async fn call_http(
...
+                status_code: Some(parts.status.as_u16()),
+                service: service_name.to_string(),
+                reason: format!("subgraph didn't return JSON (expected content-type: {} or content-type: {GRAPHQL_JSON_RESPONSE_HEADER_VALUE})", APPLICATION_JSON.essence_str()),
+            })
+        }
+    }
+}
 
-        Ok((parts, body))
-    }.instrument(subgraph_req_span).await?;
```
[the remark this answers is not in the document]
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs:678]: [3e5ce2e](https://github.com/apollographql/router/pull/3328/commits/3e5ce2e377d186526bfd527487c472fc2b867149)

[the remark this answers is not in the document]
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs:678]: Good catch

File: apollo-router/src/services/subgraph_service.rs (hunk 15 above)
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs]: This fixes cargo fmt so worth doing: [16de223](https://github.com/apollographql/router/pull/3328/commits/16de223f2ede8009d141c8d09114c3848682dba0)

File: apollo-router/src/services/subgraph_service.rs (hunk 16 above)
Comment (BrynCooke) [reply apollo-router/src/services/subgraph_service.rs]: Fixed all tests [6aec2e0](https://github.com/apollographql/router/pull/3328/commits/6aec2e00d41f4d24f2aa274783473a4b03a23b64)
