### PR TITLE
Fix redis reconnections

### LINKED ISSUE #3045: Redis client fails to reconnect after Redis outage
**Describe the bug**
After a Redis cluster goes down, it appears that the distributed caching functionality fails to reconnect afterwards. This leads to the router being in a semi-unhealthy state, but is impossible to determine without finding the pods and restarting them manually. 

**To Reproduce**
1. Run `docker run --name some-redis -p 6379:6379  -d redis` to get a Docker-ized version of Redis
2. Use the below configuration to connect to the cache. 
3. Run `docker stop some-redis` 
4. Run an APQ query against the Router - this then results in the last error, which seems to be what causes the failure to reconnect; failure to do this results in a reconnect after the next step
5. Notice errors, but eventually no attempted reconnect

Config:

```
apq:
  router:
    cache:
      redis:
        urls: ["redis://localhost:6379"]
```

**Expected behavior**
Ideally the router would reconnect on a set interval.  

**Output**
```
2023-05-04T16:19:53.100273Z  ERROR Client disconnected with error: Redis Error - kind: Canceled, details: Canceled.
2023-05-04T16:19:53.150904Z  ERROR Client disconnected with error: Redis Error - kind: IO, details: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }
2023-05-04T16:19:53.182340Z  ERROR Client disconnected with error: Redis Error - kind: IO, details: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }
2023-05-04T16:19:53.331489Z  ERROR Client disconnected with error: Redis Error - kind: IO, details: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }
2023-05-04T16:19:54.368488Z  ERROR Client disconnected with error: Redis Error - kind: IO, details: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }
2023-05-04T16:19:56.371921Z  ERROR Client disconnected with error: Redis Error - kind: IO, details: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }
2023-05-04T16:19:58.376532Z  ERROR Client disconnected with error: Redis Error - kind: IO, details: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }
2023-05-04T16:20:00.379066Z  ERROR Client disconnected with error: Redis Error - kind: IO, details: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }
2023-05-04T16:20:02.389841Z  ERROR Client disconnected with error: Redis Error - kind: IO, details: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }
2023-05-04T16:20:04.404940Z  ERROR Client disconnected with error: Redis Error - kind: IO, details: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }
2023-05-04T16:20:06.408954Z ERROR fred-uyTKYN9yai: Disconnecting after error processing command: Redis Error - kind: IO, details: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }    
2023-05-04T16:20:06.409069Z  ERROR Client disconnected with error: Redis Error - kind: IO, details: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }
```
**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS
 - Version [e.g. 22]: 1.17

### PR DESCRIPTION
**Pull request by Geal**
Fix #3045 

The reconnection policy was using an exponential backoff delay with a maximum number of attempts. Once that maximum is reached, reconnection was never tried again (there's no baseline retry). We change that behaviour by adding infinite retries with a maximum delay of 2 seconds, and a timeout of 1 millisecond on redis commands, so that the router can continue serving requests in the meantime.

This PR contains additional fixes:
- release the lock on the in memory cache while waiting for redis, to let the in memory cache serve other requests
- add a custom serializer for `SubSelectionKey`: this type is used as key in a HashMap, which is converted to a JSON object, and object keys must be strings, so a specific serializer is needed instead of the derived one

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [x] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

### CODE REVIEW

File: apollo-router/src/cache/storage.rs [hunk 1]
```diff
@@ -82,9 +82,10 @@ where
     }
 
     pub(crate) async fn get(&self, key: &K) -> Option<V> {
-        let mut guard = self.inner.lock().await;
         let instant_memory = Instant::now();
-        match guard.get(key) {
+        let res = self.inner.lock().await.get(key).cloned();
+
+        match res {
```
Comment (garypen) [inline apollo-router/src/cache/storage.rs:88]: Won't this introduce the kind of racing we are trying hard to avoid?

e.g.: If the key isn't present, then a client will get `None` and immediately release the lock. Lots of client could all call in parallel and get the same result. Then they will all (as a "thundering herd") call to redis to get the key...

Comment (Geal) [reply apollo-router/src/cache/storage.rs:88]: calls to the APQ and query planner cache, which use the dual in memory and redis cache, are gated by the deduplication code

Comment (garypen) [reply apollo-router/src/cache/storage.rs:88]: If they are gated, doesn't that mean we don't need the change?

Comment (Geal) [reply apollo-router/src/cache/storage.rs:88]: the lock is on the entire in memory cache, not per key. There can be multiple requests with different keys, so deduplication will let through one request per different key, and so if the first key got a cache miss and then queries redis, the request for the second key should not be blocked on the mutex of the in memory cache

**Review by garypen — APPROVED** [review]

**Review by o0Ignition0o — APPROVED** [review]
