### PR TITLE
Truncating Invalid Error Paths

### LINKED ISSUE #5397: Propagate errors from subgraph without hiding
Apologies if this is not a bug. Our team has invested the better part of a week trying to get this working, and we have been unsuccessful.

**Describe the bug**
We are unable to get the Router to propagate error message from our subgraphs.

In all the following scenarios, we have router config
```
include_subgraph_errors:
  all: true
```

We have a service (Service P) which is a subgraph in our supergraph. If we send a query with a bad input directly to the Service P, it returns a helpful response error:

```
{
    "errors": [
        {
            "message": "UUID cannot parse the given literal of type `StringValueNode`.",
            "path": [
                "input",
                "acceptorId"
            ],
            "extensions": {
                "field": "Foo.acceptorId",
                "fieldType": "UUID"
            }
        }
    ]
}
```
However if we send the same query to the subgraph via the Router, we get less helpful responses, depending on what `Content-Type` and `Status` we return from Service P.

- If Service P returns status `200` and content type `application/graphql-response+json; charset=utf-8` or a content-type of `application/json`, then the response we get from the router is:
```
{
    "data": null
}
```
^ The secondary concern here, is that it doesn't indicate that an error happened at all. 

- If Service P returns status `400` and content type `application/graphql-response+json; charset=utf-8`, then the response we get from the router is:

```
{
    "data": null,
    "errors": [
        {
            "message": "HTTP fetch failed from 'paymentprocessing': 400: Bad Request",
            "extensions": {
                "code": "SUBREQUEST_HTTP_ERROR",
                "service": "paymentprocessing",
                "reason": "400: Bad Request",
                "http": {
                    "status": 400
                }
            }
        }
    ]
}

```

In this case, it at least indicates that an error happened, but doesn't have any information as to why, which is a bad experience for our customers who are beginning their integration.

**To Reproduce**
1. Any schema on a subgraph behind the router.
2. Return one or more errors from subgraph on request.

**Expected behavior**
I was expecting the errors returned by the subgraph to be included in the response from the router.

**Desktop (please complete the following information):**
- We run Router in a docker container on a Arm64 Linux container.

**Additional context**
- tested on multiple version of Router, including the latest 1.48.1
- include_subgraph_errors is set for all subgraphs
- We tried different combinations of status codes and content types for the subgraph response.

**Workarounds?**
We are also interested in work arounds if anyone can provide direction for that. We already have a couple small Rhai scripts running in production, and are able to add another if required.

Thank you in advanced.

### PR DESCRIPTION
**Pull request by IvanGoncharov**
This fix addresses an issue where the router was silently dropping subgraph errors that included invalid paths.
 
According to the [GraphQL Specification](https://spec.graphql.org/draft/#sel-GAPHRPHCAACCpC8-T) an error path must point to a **response field**:
> If an error can be associated to a particular field in the GraphQL result, it must contain an entry with the key path that details the path of the response field which experienced the error.

If a subgraph error includes a path that can't be matched to a response field, the router now truncates the path to the nearest valid field path and includes the truncated portion in a `truncatedPath` extension. For example:
```json
{
    "data": { "topProducts": null },
    "errors": [{
        "message": "Some error on subgraph",
        "path": ["topProducts"],
        "extensions": {
           "service": "products",
           "truncatedPath": ["invalid", 42]
        }
    }]
}
```

Fixes #5397

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

### CODE REVIEW

File: apollo-router/src/services/execution/service.rs [hunk 1]
```diff
@@ -344,6 +344,25 @@ impl ExecutionService {
...
+                                .entry("truncatedPath")
+                                .or_insert(truncated_path);
+                        }
+
+                        // if path was invalid that means we can't trust locations either
+                        error.locations.clear();
+                    }
+                }
+            }
+
```
Comment (IvanGoncharov) [inline apollo-router/src/services/execution/service.rs:365]: Previously, we had errors with invalid paths, and they were dropped later in the pipeline.
Because code that filtered errors for primary and deferred responses couldn't match errors with invalid paths to any of the responses so it silently dropped them.

Comment (IvanGoncharov) [reply apollo-router/src/services/execution/service.rs:365]: https://github.com/apollographql/router/blob/b42ead68f93eab6eb527304e4c17647dd5dac804/apollo-router/src/services/execution/service.rs#L373-L378
https://github.com/apollographql/router/blob/b42ead68f93eab6eb527304e4c17647dd5dac804/apollo-router/src/services/execution/service.rs#L451-L457

File: apollo-router/src/spec/selection.rs [hunk 2]
```diff
@@ -189,9 +189,13 @@ impl Selection {
         })
     }
 
-    pub(crate) fn contains_error_path(&self, path: &[PathElement], fragments: &Fragments) -> bool {
+    pub(crate) fn matching_error_path_length(
```
Comment (bnjjj) [inline apollo-router/src/spec/selection.rs:192]: If we don't find anything then we return `0` right ? Why not just returning an `Option` ?

Comment (IvanGoncharov) [reply apollo-router/src/spec/selection.rs:192]: The main reason: If I put `usize` inside `Option` it would mean I need to handle both `None` and `Some(0)` as results. 

Also since this is recursive function it needs to add `+ 1` which would require more code to handle options.

File: .changesets/fix_fix_invalid_error_path.md [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+If a subgraph error includes a path that can't be matched to a response field, the router now truncates the path to the nearest valid field path and includes the truncated portion in a `truncatedPath` extension. For example:
+```json
+{
+    "data": { "topProducts": null },
+    "errors": [{
+        "message": "Some error on subgraph",
+        "path": ["topProducts"],
+        "extensions": {
+           "service": "products",
+           "truncatedPath": ["invalid", 42]
```
Comment (bnjjj) [inline .changesets/fix_fix_invalid_error_path.md:17]: I'm not sure to understand what does that mean

Comment (bnjjj) [reply .changesets/fix_fix_invalid_error_path.md:17]: Is it the field name ?

File: apollo-router/src/spec/selection.rs (hunk 2 above)
Comment (bnjjj) [reply apollo-router/src/spec/selection.rs:192]: Got it, I didn't understand `0` has a meaning

File: apollo-router/src/spec/selection.rs [hunk 4]
```diff
@@ -224,42 +234,56 @@ impl Selection {
...
+                        .max()
+                        .unwrap_or(0)
                 } else {
-                    false
+                    0
                 }
             }
             (Some(PathElement::Index(_)), _) | (Some(PathElement::Flatten(_)), _) => {
-                self.contains_error_path(&path[1..], fragments)
+                self.matching_error_path_length(&path[1..], fragments) + 1
```
Comment (bnjjj) [inline apollo-router/src/spec/selection.rs:277]: `&path[1..]` are we sure this call cannot panic ? what if we have a path size of 1 ? Does it panic ? I can't remember

Comment (goto-bus-stop) [reply apollo-router/src/spec/selection.rs:277]: if path has 1 element, then `&path[1..]` is the empty slice.

We could use `path.split_first()` at the top of this match statement instead of `path.first()` and `&path[1..]` to compile time guarantee that there can't be a panic, but it should be fine already

**Comment by goto-bus-stop** [comment]
I think the implementation looks good in principle.

I'm slightly uneasy about exposing the `truncatedPath` in extensions. Even when we added `extensions.service` some customers were surprised and considered it leaky of internal details. I think `truncatedPath` is likely to run into the same issue.

I think it could be better to land this PR *without* the extension, i.e., silently truncating paths. This would be a definite improvement over the current situation while not introducing new fields to extensions that someone could consider (rightly or wrongly) as exposing "private" details. Do you think there's a requirement for users to have access to the truncated part of the path?

File: .changesets/fix_fix_invalid_error_path.md (hunk 3 above)
Comment (IvanGoncharov) [reply .changesets/fix_fix_invalid_error_path.md:17]: @bnjjj name inside `extensions`.
Original issues is caused some GraphQL libraries trying to put path inside query arguments into the path.

For example:
```json5
{
    "errors": [
        {
            "message": "UUID cannot parse the given literal of type `StringValueNode`.",
            "path": [
                "input", 
                "acceptorId"
            ],
            "extensions": {
                "field": "Foo.acceptorId",
                "fieldType": "UUID"
            }
        }
    ]
}
```
This is invalid according to the GraphQL spec, so we should remove `path` (to be spec compliant), but the old `path` value is still useful for debugging.
Plus, if we remove a path, we switch router behavior from "silently dropping errors" to "silently dropping path inside errors".
My idea is to put the truncated part inside extensions as `truncatedPath`, so above error would be change to this:
```
{
    "errors": [
        {
            "message": "UUID cannot parse the given literal of type `StringValueNode`.",
            "extensions": {
                "field": "Foo.acceptorId",
                "fieldType": "UUID"
                "path": [
                    "input", 
                    "acceptorId"
                ],
            }
        }
    ]
}
```

**Comment by IvanGoncharov** [comment]
>  Even when we added extensions.service some customers were surprised and considered it leaky of internal details. I think truncatedPath is likely to run into the same issue.

@goto-bus-stop Yes, you are right.
I just saw #6402, and it explains why this is problematic.
I think `truncatedPath` is helpful, but I agree it should be added after #6402 or something similar is merged.
I will split it into separate draft PRs so as not to lose it.

File: .changesets/fix_fix_invalid_error_path.md (hunk 3 above)
Comment (IvanGoncharov) [reply .changesets/fix_fix_invalid_error_path.md:17]: I will split it up in a separate PR as discussed here: https://github.com/apollographql/router/pull/6359#issuecomment-2535841673

File: apollo-router/src/spec/selection.rs (hunk 4 above)
Comment (bnjjj) [reply apollo-router/src/spec/selection.rs:273]: @IvanGoncharov I saw you used `split_first` but you're not using the second part of this `split_first`here instead of `&path[1..]`

**Review by bnjjj — APPROVED** [review]
